rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference
JSON Schema Validator.
#include <fwd.h>
Public Types
typedef SchemaDocumentType::SchemaType SchemaType
typedef SchemaDocumentType::PointerType PointerType
typedef SchemaType::EncodingType EncodingType
typedef SchemaType::SValue SValue
typedef EncodingType::Ch Ch
typedef GenericStringRef< Ch > StringRefType
typedef GenericValue< EncodingType, StateAllocator > ValueType
Public Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor without output handler.
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, OutputHandler &outputHandler, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor with output handler.
~GenericSchemaValidator ()
Destructor.
void Reset ()
Reset the internal states.
virtual bool IsValid () const
Checks whether the current state is valid.
ValueType & GetError ()
Gets the error object.
const ValueType & GetError () const
PointerType GetInvalidSchemaPointer () const
Gets the JSON pointer pointed to the invalid schema.
const Ch * GetInvalidSchemaKeyword () const
Gets the keyword of invalid schema.
PointerType GetInvalidDocumentPointer () const
Gets the JSON pointer pointed to the invalid value.
void NotMultipleOf (int64_t actual, const SValue &expected)
void NotMultipleOf (uint64_t actual, const SValue &expected)
void NotMultipleOf (double actual, const SValue &expected)
void AboveMaximum (int64_t actual, const SValue &expected, bool exclusive)
void AboveMaximum (uint64_t actual, const SValue &expected, bool exclusive)
void AboveMaximum (double actual, const SValue &expected, bool exclusive)
void BelowMinimum (int64_t actual, const SValue &expected, bool exclusive)
void BelowMinimum (uint64_t actual, const SValue &expected, bool exclusive)
void BelowMinimum (double actual, const SValue &expected, bool exclusive)
void TooLong (const Ch *str, SizeType length, SizeType expected)
void TooShort (const Ch *str, SizeType length, SizeType expected)
void DoesNotMatch (const Ch *str, SizeType length)
void DisallowedItem (SizeType index)
void TooFewItems (SizeType actualCount, SizeType expectedCount)
void TooManyItems (SizeType actualCount, SizeType expectedCount)
void DuplicateItems (SizeType index1, SizeType index2)
void TooManyProperties (SizeType actualCount, SizeType expectedCount)
void TooFewProperties (SizeType actualCount, SizeType expectedCount)
void StartMissingProperties ()
void AddMissingProperty (const SValue &name)
bool EndMissingProperties ()
void PropertyViolations (ISchemaValidator **subvalidators, SizeType count)
void DisallowedProperty (const Ch *name, SizeType length)
void StartDependencyErrors ()
void StartMissingDependentProperties ()
void AddMissingDependentProperty (const SValue &targetName)
void EndMissingDependentProperties (const SValue &sourceName)
void AddDependencySchemaError (const SValue &sourceName, ISchemaValidator *subvalidator)
bool EndDependencyErrors ()
void DisallowedValue ()
void StartDisallowedType ()
void AddExpectedType (const typename SchemaType::ValueType &expectedType)
void EndDisallowedType (const typename SchemaType::ValueType &actualType)
void NotAllOf (ISchemaValidator **subvalidators, SizeType count)
void NoneOf (ISchemaValidator **subvalidators, SizeType count)
void NotOneOf (ISchemaValidator **subvalidators, SizeType count)
void Disallowed ()
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType length, bool copy)
bool String (const Ch *str, SizeType length, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType len, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
virtual ISchemaValidator * CreateSchemaValidator (const SchemaType &root)
virtual void DestroySchemaValidator (ISchemaValidator *validator)
virtual void * CreateHasher ()
virtual uint64_t GetHashCode (void *hasher)
virtual void DestroryHasher (void *hasher)
virtual void * MallocState (size_t size)
virtual void FreeState (void *p)
Static Public Member Functions
static const StringRefType & GetInstanceRefString ()
static const StringRefType & GetSchemaRefString ()
static const StringRefType & GetExpectedString ()
static const StringRefType & GetActualString ()
static const StringRefType & GetDisallowedString ()
static const StringRefType & GetMissingString ()
static const StringRefType & GetErrorsString ()
static const StringRefType & GetDuplicatesString ()
Private Types
typedef SchemaType::Context Context
typedef GenericValue< UTF8<>, StateAllocator > HashCodeArray
typedef internal::Hasher< EncodingType, StateAllocator > HasherType
Private Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, const SchemaType &root, const char *basePath, size_t basePathSize, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
StateAllocator & GetStateAllocator ()
bool BeginValue ()
bool EndValue ()
void AppendToken (const Ch *str, SizeType len)
RAPIDJSON_FORCEINLINE void PushSchema (const SchemaType &schema)
RAPIDJSON_FORCEINLINE void PopSchema ()
void AddErrorLocation (ValueType &result, bool parent)
void AddError (ValueType &keyword, ValueType &error)
void AddCurrentError (const typename SchemaType::ValueType &keyword, bool parent=false)
void MergeError (ValueType &other)
void AddNumberError (const typename SchemaType::ValueType &keyword, ValueType &actual, const SValue &expected, const typename SchemaType::ValueType &(*exclusive)()=0)
void AddErrorArray (const typename SchemaType::ValueType &keyword, ISchemaValidator **subvalidators, SizeType count)
const SchemaType & CurrentSchema () const
Context & CurrentContext ()
const Context & CurrentContext () const
Private Attributes
const SchemaDocumentType * schemaDocument_
const SchemaType & root_
StateAllocator * stateAllocator_
StateAllocator * ownStateAllocator_
internal::Stack< StateAllocator > schemaStack_
stack to store the current path of schema (BaseSchemaType *)
internal::Stack< StateAllocator > documentStack_
stack to store the current path of validating document (Ch)
OutputHandler * outputHandler_
ValueType error_
ValueType currentError_
ValueType missingDependents_
bool valid_
Static Private Attributes
static const size_t kDefaultSchemaStackCapacity = 1024
static const size_t kDefaultDocumentStackCapacity = 256
Detailed Description
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
class rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >
JSON Schema Validator.
A SAX style JSON schema validator. It uses a GenericSchemaDocument to validate SAX events. It delegates the incoming SAX events to an output handler. The default output handler does nothing. It can be reused multiple times by calling Reset().
Template Parameters
SchemaDocumentType Type of schema document.
OutputHandler Type of output handler. Default handler does nothing.
StateAllocator Allocator for storing the internal validation states.
Definition at line 145 of file fwd.h.
Member Typedef Documentation
Ch
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef EncodingType::Ch rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Ch
Definition at line 1773 of file schema.h.
Context
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef SchemaType::Context rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Context [private]
Definition at line 2192 of file schema.h.
EncodingType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef SchemaType::EncodingType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EncodingType
Definition at line 1771 of file schema.h.
HashCodeArray
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef GenericValue<UTF8<>, StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::HashCodeArray [private]
Definition at line 2193 of file schema.h.
HasherType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef internal::Hasher<EncodingType, StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::HasherType [private]
Definition at line 2194 of file schema.h.
PointerType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef SchemaDocumentType::PointerType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PointerType
Definition at line 1770 of file schema.h.
SchemaType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef SchemaDocumentType::SchemaType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SchemaType
Definition at line 1769 of file schema.h.
StringRefType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef GenericStringRef<Ch> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StringRefType
Definition at line 1774 of file schema.h.
SValue
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef SchemaType::SValue rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SValue
Definition at line 1772 of file schema.h.
ValueType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
typedef GenericValue<EncodingType, StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ValueType
Definition at line 1775 of file schema.h.
Constructor & Destructor Documentation
GenericSchemaValidator() [1/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity)
Constructor without output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Definition at line 1784 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(schemaDocument.GetRoot()),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(0),
        error_(kObjectType),
        currentError_(),
        missingDependents_(),
        valid_(true)
#if RAPIDJSON_SCHEMA_VERBOSE
        , depth_(0)
#endif
    {
    }
GenericSchemaValidator() [2/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, OutputHandler & outputHandler, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity)
Constructor with output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Definition at line 1814 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(schemaDocument.GetRoot()),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(&outputHandler),
        error_(kObjectType),
        currentError_(),
        missingDependents_(),
        valid_(true)
#if RAPIDJSON_SCHEMA_VERBOSE
        , depth_(0)
#endif
    {
    }
 GenericSchemaValidator()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator ()
Destructor.
Definition at line 1839 of file schema.h.
                              {
        Reset();
        RAPIDJSON_DELETE(ownStateAllocator_);
    }
References RAPIDJSON_DELETE.
Referenced by rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator().
GenericSchemaValidator() [3/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, const SchemaType & root, const char * basePath, size_t basePathSize, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) [private]
Definition at line 2196 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(root),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(0),
        error_(kObjectType),
        currentError_(),
        missingDependents_(),
        valid_(true)
#if RAPIDJSON_SCHEMA_VERBOSE
        , depth_(depth)
#endif
    {
        if (basePath && basePathSize)
            memcpy(documentStack_.template Push<char>(basePathSize), basePath, basePathSize);
    }
Member Function Documentation
AboveMaximum() [1/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (int64_t actual, const SValue & expected, bool exclusive)
Definition at line 1892 of file schema.h.
                                                                              {
        AddNumberError(SchemaType::GetMaximumString(), ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMaximumString : 0);
    }
AboveMaximum() [2/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (uint64_t actual, const SValue & expected, bool exclusive)
Definition at line 1896 of file schema.h.
                                                                               {
        AddNumberError(SchemaType::GetMaximumString(), ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMaximumString : 0);
    }
AboveMaximum() [3/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (double actual, const SValue & expected, bool exclusive)
Definition at line 1900 of file schema.h.
                                                                             {
        AddNumberError(SchemaType::GetMaximumString(), ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMaximumString : 0);
    }
AddCurrentError()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddCurrentError (const typename SchemaType::ValueType & keyword, bool parent = false) [private]
Definition at line 2363 of file schema.h.
                                                                                           {
        AddErrorLocation(currentError_, parent);
        AddError(ValueType(keyword, GetStateAllocator(), false).Move(), currentError_);
    }
AddDependencySchemaError()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddDependencySchemaError (const SValue & sourceName, ISchemaValidator * subvalidator)
Definition at line 2000 of file schema.h.
                                                                                            {
        currentError_.AddMember(ValueType(sourceName, GetStateAllocator()).Move(),
            static_cast<GenericSchemaValidator*>(subvalidator)->GetError(), GetStateAllocator());
    }
AddError()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddError (ValueType & keyword, ValueType & error) [private]
Definition at line 2349 of file schema.h.
                                                        {
        typename ValueType::MemberIterator member = error_.FindMember(keyword);
        if (member == error_.MemberEnd())
            error_.AddMember(keyword, error, GetStateAllocator());
        else {
            if (member->value.IsObject()) {
                ValueType errors(kArrayType);
                errors.PushBack(member->value, GetStateAllocator());
                member->value = errors;
            }
            member->value.PushBack(error, GetStateAllocator());
        }
    }
References rapidjson::kArrayType.
AddErrorArray()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorArray (const typename SchemaType::ValueType & keyword, ISchemaValidator ** subvalidators, SizeType count) [private]
Definition at line 2384 of file schema.h.
                                                          {
        ValueType errors(kArrayType);
        for (SizeType i = 0; i < count; ++i)
            errors.PushBack(static_cast<GenericSchemaValidator*>(subvalidators[i])->GetError(), GetStateAllocator());
        currentError_.SetObject();
        currentError_.AddMember(GetErrorsString(), errors, GetStateAllocator());
        AddCurrentError(keyword);
    }
References rapidjson::kArrayType.
AddErrorLocation()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddErrorLocation (ValueType & result, bool parent) [private]
Definition at line 2330 of file schema.h.
                                                          {
        GenericStringBuffer<EncodingType> sb;
        PointerType instancePointer = GetInvalidDocumentPointer();
        ((parent && instancePointer.GetTokenCount() > 0)
            ? PointerType(instancePointer.GetTokens(), instancePointer.GetTokenCount() - 1)
            : instancePointer).StringifyUriFragment(sb);
        ValueType instanceRef(sb.GetString(), static_cast<SizeType>(sb.GetSize() / sizeof(Ch)),
            GetStateAllocator());
        result.AddMember(GetInstanceRefString(), instanceRef, GetStateAllocator());
        sb.Clear();
        memcpy(sb.Push(CurrentSchema().GetURI().GetStringLength()),
            CurrentSchema().GetURI().GetString(),
            CurrentSchema().GetURI().GetStringLength() * sizeof(Ch));
        GetInvalidSchemaPointer().StringifyUriFragment(sb);
        ValueType schemaRef(sb.GetString(), static_cast<SizeType>(sb.GetSize() / sizeof(Ch)),
            GetStateAllocator());
        result.AddMember(GetSchemaRefString(), schemaRef, GetStateAllocator());
    }
References rapidjson::GenericStringBuffer< Encoding, Allocator >::Clear(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetSize(), rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), and rapidjson::GenericStringBuffer< Encoding, Allocator >::Push().
AddExpectedType()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddExpectedType (const typename SchemaType::ValueType & expectedType)
Definition at line 2021 of file schema.h.
                                                                           {
        currentError_.PushBack(ValueType(expectedType, GetStateAllocator()).Move(), GetStateAllocator());
    }
AddMissingDependentProperty()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddMissingDependentProperty (const SValue & targetName)
Definition at line 1992 of file schema.h.
                                                               {
        missingDependents_.PushBack(ValueType(targetName, GetStateAllocator()).Move(), GetStateAllocator());
    }
AddMissingProperty()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddMissingProperty (const SValue & name)
Definition at line 1964 of file schema.h.
                                                {
        currentError_.PushBack(ValueType(name, GetStateAllocator()).Move(), GetStateAllocator());
    }
AddNumberError()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddNumberError (const typename SchemaType::ValueType & keyword, ValueType & actual, const SValue & expected, const typename SchemaType::ValueType &(*)() exclusive = 0) [private]
Definition at line 2374 of file schema.h.
                                                                {
        currentError_.SetObject();
        currentError_.AddMember(GetActualString(), actual, GetStateAllocator());
        currentError_.AddMember(GetExpectedString(), ValueType(expected, GetStateAllocator()).Move(), GetStateAllocator());
        if (exclusive)
            currentError_.AddMember(ValueType(exclusive(), GetStateAllocator()).Move(), true, GetStateAllocator());
        AddCurrentError(keyword);
    }
AppendToken()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AppendToken (const Ch * str, SizeType len) [private]
Definition at line 2302 of file schema.h.
                                                  {
        documentStack_.template Reserve<Ch>(1 + len * 2); // worst case all characters are escaped as two characters
        *documentStack_.template PushUnsafe<Ch>() = '/';
        for (SizeType i = 0; i < len; i++) {
            if (str[i] == ' ') {
                *documentStack_.template PushUnsafe<Ch>() = ' ';
                *documentStack_.template PushUnsafe<Ch>() = '0';
            }
            else if (str[i] == '/') {
                *documentStack_.template PushUnsafe<Ch>() = ' ';
                *documentStack_.template PushUnsafe<Ch>() = '1';
            }
            else
                *documentStack_.template PushUnsafe<Ch>() = str[i];
        }
    }
BeginValue()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue () [private]
Definition at line 2232 of file schema.h.
                      {
        if (schemaStack_.Empty())
            PushSchema(root_);
        else {
            if (CurrentContext().inArray)
                internal::TokenHelper<internal::Stack<StateAllocator>, Ch>::AppendIndexToken(documentStack_, CurrentContext().arrayElementIndex);
            if (!CurrentSchema().BeginValue(CurrentContext()))
                return false;
            SizeType count = CurrentContext().patternPropertiesSchemaCount;
            const SchemaType** sa = CurrentContext().patternPropertiesSchemas;
            typename Context::PatternValidatorType patternValidatorType = CurrentContext().valuePatternValidatorType;
            bool valueUniqueness = CurrentContext().valueUniqueness;
            RAPIDJSON_ASSERT(CurrentContext().valueSchema);
            PushSchema(*CurrentContext().valueSchema);
            if (count > 0) {
                CurrentContext().objectPatternValidatorType = patternValidatorType;
                ISchemaValidator**& va = CurrentContext().patternPropertiesValidators;
                SizeType& validatorCount = CurrentContext().patternPropertiesValidatorCount;
                va = static_cast<ISchemaValidator**>(MallocState(sizeof(ISchemaValidator*) * count));
                for (SizeType i = 0; i < count; i++)
                    va[validatorCount++] = CreateSchemaValidator(*sa[i]);
            }
            CurrentContext().arrayUniqueness = valueUniqueness;
        }
        return true;
    }
References RAPIDJSON_ASSERT.
BelowMinimum() [1/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (int64_t actual, const SValue & expected, bool exclusive)
Definition at line 1904 of file schema.h.
                                                                              {
        AddNumberError(SchemaType::GetMinimumString(), ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMinimumString : 0);
    }
BelowMinimum() [2/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (uint64_t actual, const SValue & expected, bool exclusive)
Definition at line 1908 of file schema.h.
                                                                               {
        AddNumberError(SchemaType::GetMinimumString(), ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMinimumString : 0);
    }
BelowMinimum() [3/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (double actual, const SValue & expected, bool exclusive)
Definition at line 1912 of file schema.h.
                                                                             {
        AddNumberError(SchemaType::GetMinimumString(), ValueType(actual).Move(), expected,
            exclusive ? &SchemaType::GetExclusiveMinimumString : 0);
    }
Bool()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool (bool b)
Definition at line 2104 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Bool, (CurrentContext(), b), (b)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
CreateHasher()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual void* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateHasher () [virtual]
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2169 of file schema.h.
                                 {
        return new (GetStateAllocator().Malloc(sizeof(HasherType))) HasherType(&GetStateAllocator());
    }
CreateSchemaValidator()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual ISchemaValidator* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator (const SchemaType & root) [virtual]
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2155 of file schema.h.
                                                                            {
        return new (GetStateAllocator().Malloc(sizeof(GenericSchemaValidator))) GenericSchemaValidator(*schemaDocument_, root, documentStack_.template Bottom<char>(), documentStack_.GetSize(),
#if RAPIDJSON_SCHEMA_VERBOSE
        depth_ + 1,
#endif
        &GetStateAllocator());
    }
CurrentContext() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
Context& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext () [private]
Definition at line 2395 of file schema.h.
{ return *schemaStack_.template Top<Context>(); }
CurrentContext() [2/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const Context& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext () const [private]
Definition at line 2396 of file schema.h.
{ return *schemaStack_.template Top<Context>(); }
CurrentSchema()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const SchemaType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema () const [private]
Definition at line 2394 of file schema.h.
{ return *schemaStack_.template Top<Context>()->schema; }
DestroryHasher()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroryHasher (void * hasher) [virtual]
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2177 of file schema.h.
                                              {
        HasherType* h = static_cast<HasherType*>(hasher);
        h-> HasherType();
        StateAllocator::Free(h);
    }
DestroySchemaValidator()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator (ISchemaValidator * validator) [virtual]
Definition at line 2163 of file schema.h.
                                                                     {
        GenericSchemaValidator* v = static_cast<GenericSchemaValidator*>(validator);
        v-> GenericSchemaValidator();
        StateAllocator::Free(v);
    }
References rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator().
Disallowed()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Disallowed () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2042 of file schema.h.
                      {
        currentError_.SetObject();
        AddCurrentError(SchemaType::GetNotString());
    }
DisallowedItem()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedItem (SizeType index) [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1931 of file schema.h.
                                        {
        currentError_.SetObject();
        currentError_.AddMember(GetDisallowedString(), ValueType(index).Move(), GetStateAllocator());
        AddCurrentError(SchemaType::GetAdditionalItemsString(), true);
    }
DisallowedProperty()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedProperty (const Ch * name, SizeType length)
Definition at line 1980 of file schema.h.
                                                             {
        currentError_.SetObject();
        currentError_.AddMember(GetDisallowedString(), ValueType(name, length, GetStateAllocator()).Move(), GetStateAllocator());
        AddCurrentError(SchemaType::GetAdditionalPropertiesString(), true);
    }
DisallowedValue()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedValue () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2014 of file schema.h.
                           {
        currentError_.SetObject();
        AddCurrentError(SchemaType::GetEnumString());
    }
DoesNotMatch()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DoesNotMatch (const Ch * str, SizeType length)
Definition at line 1925 of file schema.h.
                                                      {
        currentError_.SetObject();
        currentError_.AddMember(GetActualString(), ValueType(str, length, GetStateAllocator()).Move(), GetStateAllocator());
        AddCurrentError(SchemaType::GetPatternString());
    }
Double()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double (double d)
Definition at line 2109 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Double, (CurrentContext(), d), (d)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
DuplicateItems()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DuplicateItems (SizeType index1, SizeType index2) [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1944 of file schema.h.
                                                          {
        ValueType duplicates(kArrayType);
        duplicates.PushBack(index1, GetStateAllocator());
        duplicates.PushBack(index2, GetStateAllocator());
        currentError_.SetObject();
        currentError_.AddMember(GetDuplicatesString(), duplicates, GetStateAllocator());
        AddCurrentError(SchemaType::GetUniqueItemsString(), true);
    }
References rapidjson::kArrayType.
EndArray()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray (SizeType elementCount)
Definition at line 2142 of file schema.h.
                                         {
        if (!valid_) return false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndArray, (elementCount));
        if (!CurrentSchema().EndArray(CurrentContext(), elementCount)) return valid_ = false;
        RAPIDJSON_SCHEMA_HANDLE_END_(EndArray, (elementCount));
    }
References RAPIDJSON_SCHEMA_HANDLE_END_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
EndDependencyErrors()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndDependencyErrors () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2004 of file schema.h.
                               {
        if (currentError_.ObjectEmpty())
            return false;
        ValueType error(kObjectType);
        error.AddMember(GetErrorsString(), currentError_, GetStateAllocator());
        currentError_ = error;
        AddCurrentError(SchemaType::GetDependenciesString());
        return true;
    }
References rapidjson::kObjectType.
EndDisallowedType()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndDisallowedType (const typename SchemaType::ValueType & actualType)
Definition at line 2024 of file schema.h.
                                                                           {
        ValueType error(kObjectType);
        error.AddMember(GetExpectedString(), currentError_, GetStateAllocator());
        error.AddMember(GetActualString(), ValueType(actualType, GetStateAllocator()).Move(), GetStateAllocator());
        currentError_ = error;
        AddCurrentError(SchemaType::GetTypeString());
    }
References rapidjson::kObjectType.
EndMissingDependentProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndMissingDependentProperties (const SValue & sourceName)
Definition at line 1995 of file schema.h.
                                                                 {
        if (!missingDependents_.Empty())
            currentError_.AddMember(ValueType(sourceName, GetStateAllocator()).Move(),
                missingDependents_, GetStateAllocator());
    }
EndMissingProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndMissingProperties () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1967 of file schema.h.
                                {
        if (currentError_.Empty())
            return false;
        ValueType error(kObjectType);
        error.AddMember(GetMissingString(), currentError_, GetStateAllocator());
        currentError_ = error;
        AddCurrentError(SchemaType::GetRequiredString());
        return true;
    }
References rapidjson::kObjectType.
EndObject()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject (SizeType memberCount)
Definition at line 2129 of file schema.h.
                                         {
        if (!valid_) return false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndObject, (memberCount));
        if (!CurrentSchema().EndObject(CurrentContext(), memberCount)) return valid_ = false;
        RAPIDJSON_SCHEMA_HANDLE_END_(EndObject, (memberCount));
    }
References RAPIDJSON_SCHEMA_HANDLE_END_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
EndValue()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue () [private]
Definition at line 2263 of file schema.h.
                    {
        if (!CurrentSchema().EndValue(CurrentContext()))
            return false;
#if RAPIDJSON_SCHEMA_VERBOSE
        GenericStringBuffer<EncodingType> sb;
        schemaDocument_->GetPointer(&CurrentSchema()).Stringify(sb);
        *documentStack_.template Push<Ch>() = '\0';
        documentStack_.template Pop<Ch>(1);
        internal::PrintValidatorPointers(depth_, sb.GetString(), documentStack_.template Bottom<Ch>());
#endif
        uint64_t h = CurrentContext().arrayUniqueness ? static_cast<HasherType*>(CurrentContext().hasher)->GetHashCode() : 0;
        
        PopSchema();
        if (!schemaStack_.Empty()) {
            Context& context = CurrentContext();
            if (context.valueUniqueness) {
                HashCodeArray* a = static_cast<HashCodeArray*>(context.arrayElementHashCodes);
                if (!a)
                    CurrentContext().arrayElementHashCodes = a = new (GetStateAllocator().Malloc(sizeof(HashCodeArray))) HashCodeArray(kArrayType);
                for (typename HashCodeArray::ConstValueIterator itr = a->Begin(); itr != a->End(); ++itr)
                    if (itr->GetUint64() == h) {
                        DuplicateItems(static_cast<SizeType>(itr - a->Begin()), a->Size());
                        RAPIDJSON_INVALID_KEYWORD_RETURN(SchemaType::GetUniqueItemsString());
                    }
                a->PushBack(h, GetStateAllocator());
            }
        }
        // Remove the last token of document pointer
        while (!documentStack_.Empty() && *documentStack_.template Pop<Ch>(1) != '/')
            ;
        return true;
    }
References rapidjson::a, rapidjson::GenericStringBuffer< Encoding, Allocator >::GetString(), rapidjson::kArrayType, and RAPIDJSON_INVALID_KEYWORD_RETURN.
FreeState()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::FreeState (void * p) [virtual]
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2187 of file schema.h.
                                    {
        StateAllocator::Free(p);
    }
GetActualString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetActualString () [static]
Definition at line 2057 of file schema.h.
GetDisallowedString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetDisallowedString () [static]
Definition at line 2058 of file schema.h.
GetDuplicatesString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetDuplicatesString () [static]
Definition at line 2061 of file schema.h.
GetError() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
ValueType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError ()
Gets the error object.
Definition at line 1860 of file schema.h.
{ return error_; }
Referenced by rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetError() [2/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const ValueType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError () const
Definition at line 1861 of file schema.h.
{ return error_; }
GetErrorsString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetErrorsString () [static]
Definition at line 2060 of file schema.h.
GetExpectedString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetExpectedString () [static]
Definition at line 2056 of file schema.h.
GetHashCode()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual uint64_t rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode (void * hasher) [virtual]
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2173 of file schema.h.
                                               {
        return static_cast<HasherType*>(hasher)->GetHashCode();
    }
GetInstanceRefString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInstanceRefString () [static]
Definition at line 2054 of file schema.h.
GetInvalidDocumentPointer()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
PointerType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer () const
Gets the JSON pointer pointed to the invalid value.
Definition at line 1874 of file schema.h.
                                                  {
        if (documentStack_.Empty()) {
            return PointerType();
        }
        else {
            return PointerType(documentStack_.template Bottom<Ch>(), documentStack_.GetSize() / sizeof(Ch));
        }
    }
Referenced by rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetInvalidSchemaKeyword()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const Ch* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword () const
Gets the keyword of invalid schema.
Definition at line 1869 of file schema.h.
                                              {
        return schemaStack_.Empty() ? 0 : CurrentContext().invalidKeyword;
    }
Referenced by rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetInvalidSchemaPointer()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
PointerType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer () const
Gets the JSON pointer pointed to the invalid schema.
Definition at line 1864 of file schema.h.
                                                {
        return schemaStack_.Empty() ? PointerType() : CurrentSchema().GetPointer();
    }
Referenced by rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetMissingString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetMissingString () [static]
Definition at line 2059 of file schema.h.
GetSchemaRefString()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
static const StringRefType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetSchemaRefString () [static]
Definition at line 2055 of file schema.h.
GetStateAllocator()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
StateAllocator& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator () [private]
Definition at line 2226 of file schema.h.
                                        {
        if (!stateAllocator_)
            stateAllocator_ = ownStateAllocator_ = RAPIDJSON_NEW(StateAllocator)();
        return *stateAllocator_;
    }
References RAPIDJSON_NEW.
Int()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int (int i)
Definition at line 2105 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Int, (CurrentContext(), i), (i)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Int64()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64 (int64_t i)
Definition at line 2107 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Int64, (CurrentContext(), i), (i)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
IsValid()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid () const [virtual]
Checks whether the current state is valid.
Implements rapidjson::internal::ISchemaValidator.
Definition at line 1857 of file schema.h.
{ return valid_; }
Referenced by rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
Key()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key (const Ch * str, SizeType len, bool copy)
Definition at line 2121 of file schema.h.
                                                     {
        if (!valid_) return false;
        AppendToken(str, len);
        if (!CurrentSchema().Key(CurrentContext(), str, len, copy)) return valid_ = false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(Key, (str, len, copy));
        return valid_ = !outputHandler_ || outputHandler_->Key(str, len, copy);
    }
References RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
MallocState()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
virtual void* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MallocState (size_t size) [virtual]
Implements rapidjson::internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 2183 of file schema.h.
                                           {
        return GetStateAllocator().Malloc(size);
    }
MergeError()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MergeError (ValueType & other) [private]
Definition at line 2368 of file schema.h.
                                      {
        for (typename ValueType::MemberIterator it = other.MemberBegin(), end = other.MemberEnd(); it != end; ++it) {
            AddError(it->name, it->value);
        }
    }
NoneOf()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NoneOf (ISchemaValidator ** subvalidators, SizeType count)
Definition at line 2036 of file schema.h.
                                                                  {
        AddErrorArray(SchemaType::GetAnyOfString(), subvalidators, count);
    }
NotAllOf()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotAllOf (ISchemaValidator ** subvalidators, SizeType count)
Definition at line 2031 of file schema.h.
                                                                    {
        for (SizeType i = 0; i < count; ++i) {
            MergeError(static_cast<GenericSchemaValidator*>(subvalidators[i])->GetError());
        }
    }
NotMultipleOf() [1/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (int64_t actual, const SValue & expected)
Definition at line 1883 of file schema.h.
                                                               {
        AddNumberError(SchemaType::GetMultipleOfString(), ValueType(actual).Move(), expected);
    }
NotMultipleOf() [2/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (uint64_t actual, const SValue & expected)
Definition at line 1886 of file schema.h.
                                                                {
        AddNumberError(SchemaType::GetMultipleOfString(), ValueType(actual).Move(), expected);
    }
NotMultipleOf() [3/3]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (double actual, const SValue & expected)
Definition at line 1889 of file schema.h.
                                                              {
        AddNumberError(SchemaType::GetMultipleOfString(), ValueType(actual).Move(), expected);
    }
NotOneOf()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotOneOf (ISchemaValidator ** subvalidators, SizeType count)
Definition at line 2039 of file schema.h.
                                                                    {
        AddErrorArray(SchemaType::GetOneOfString(), subvalidators, count);
    }
Null()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null ()
Definition at line 2103 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Null, (CurrentContext()), ()); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
PopSchema()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
RAPIDJSON_FORCEINLINE void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema () [private]
Definition at line 2321 of file schema.h.
                                           {
        Context* c = schemaStack_.template Pop<Context>(1);
        if (HashCodeArray* a = static_cast<HashCodeArray*>(c->arrayElementHashCodes)) {
            a-> HashCodeArray();
            StateAllocator::Free(a);
        }
        c-> Context();
    }
References rapidjson::a.
PropertyViolations()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PropertyViolations (ISchemaValidator ** subvalidators, SizeType count)
Definition at line 1976 of file schema.h.
                                                                              {
        for (SizeType i = 0; i < count; ++i)
            MergeError(static_cast<GenericSchemaValidator*>(subvalidators[i])->GetError());
    }
PushSchema()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
RAPIDJSON_FORCEINLINE void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PushSchema (const SchemaType & schema) [private]
Definition at line 2319 of file schema.h.
{ new (schemaStack_.template Push<Context>()) Context(*this, *this, &schema); }
RawNumber()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber (const Ch * str, SizeType length, bool copy)
Definition at line 2110 of file schema.h.
                                    { RAPIDJSON_SCHEMA_HANDLE_VALUE_(String, (CurrentContext(), str, length, copy), (str, length, copy)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Reset()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset ()
Reset the internal states.
Definition at line 1845 of file schema.h.
                 {
        while (!schemaStack_.Empty())
            PopSchema();
        documentStack_.Clear();
        error_.SetObject();
        currentError_.SetNull();
        missingDependents_.SetNull();
        valid_ = true;
    }
StartArray()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray ()
Definition at line 2136 of file schema.h.
                      {
        RAPIDJSON_SCHEMA_HANDLE_BEGIN_(StartArray, (CurrentContext()));
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(StartArray, ());
        return valid_ = !outputHandler_ || outputHandler_->StartArray();
    }
References RAPIDJSON_SCHEMA_HANDLE_BEGIN_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
StartDependencyErrors()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartDependencyErrors () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1986 of file schema.h.
                                 {
        currentError_.SetObject();
    }
StartDisallowedType()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartDisallowedType () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 2018 of file schema.h.
                               {
        currentError_.SetArray();
    }
StartMissingDependentProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartMissingDependentProperties () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1989 of file schema.h.
                                           {
        missingDependents_.SetArray();
    }
StartMissingProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartMissingProperties () [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1961 of file schema.h.
                                  {
        currentError_.SetArray();
    }
StartObject()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject ()
Definition at line 2115 of file schema.h.
                       {
        RAPIDJSON_SCHEMA_HANDLE_BEGIN_(StartObject, (CurrentContext()));
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(StartObject, ());
        return valid_ = !outputHandler_ || outputHandler_->StartObject();
    }
References RAPIDJSON_SCHEMA_HANDLE_BEGIN_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
String()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String (const Ch * str, SizeType length, bool copy)
Definition at line 2112 of file schema.h.
                                    { RAPIDJSON_SCHEMA_HANDLE_VALUE_(String, (CurrentContext(), str, length, copy), (str, length, copy)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
TooFewItems()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooFewItems (SizeType actualCount, SizeType expectedCount) [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1936 of file schema.h.
                                                                   {
        AddNumberError(SchemaType::GetMinItemsString(),
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
TooFewProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooFewProperties (SizeType actualCount, SizeType expectedCount) [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1957 of file schema.h.
                                                                        {
        AddNumberError(SchemaType::GetMinPropertiesString(),
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
TooLong()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooLong (const Ch * str, SizeType length, SizeType expected)
Definition at line 1917 of file schema.h.
                                                                    {
        AddNumberError(SchemaType::GetMaxLengthString(),
            ValueType(str, length, GetStateAllocator()).Move(), SValue(expected).Move());
    }
TooManyItems()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooManyItems (SizeType actualCount, SizeType expectedCount) [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1940 of file schema.h.
                                                                    {
        AddNumberError(SchemaType::GetMaxItemsString(),
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
TooManyProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooManyProperties (SizeType actualCount, SizeType expectedCount) [virtual]
Implements rapidjson::internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Definition at line 1953 of file schema.h.
                                                                         {
        AddNumberError(SchemaType::GetMaxPropertiesString(),
            ValueType(actualCount).Move(), SValue(expectedCount).Move());
    }
TooShort()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
void rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooShort (const Ch * str, SizeType length, SizeType expected)
Definition at line 1921 of file schema.h.
                                                                     {
        AddNumberError(SchemaType::GetMinLengthString(),
            ValueType(str, length, GetStateAllocator()).Move(), SValue(expected).Move());
    }
Uint()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint (unsigned u)
Definition at line 2106 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Uint, (CurrentContext(), u), (u)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Uint64()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64 (uint64_t u)
Definition at line 2108 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Uint64, (CurrentContext(), u), (u)); }
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Field Documentation
currentError_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
ValueType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::currentError_ [private]
Definition at line 2408 of file schema.h.
documentStack_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
internal::Stack<StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_ [private]
stack to store the current path of validating document (Ch)
Definition at line 2405 of file schema.h.
error_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
ValueType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::error_ [private]
Definition at line 2407 of file schema.h.
kDefaultDocumentStackCapacity
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const size_t rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::kDefaultDocumentStackCapacity = 256 [static], [private]
Definition at line 2399 of file schema.h.
kDefaultSchemaStackCapacity
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const size_t rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::kDefaultSchemaStackCapacity = 1024 [static], [private]
Definition at line 2398 of file schema.h.
missingDependents_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
ValueType rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::missingDependents_ [private]
Definition at line 2409 of file schema.h.
outputHandler_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
OutputHandler* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::outputHandler_ [private]
Definition at line 2406 of file schema.h.
ownStateAllocator_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
StateAllocator* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ownStateAllocator_ [private]
Definition at line 2403 of file schema.h.
root_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const SchemaType& rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::root_ [private]
Definition at line 2401 of file schema.h.
schemaDocument_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
const SchemaDocumentType* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaDocument_ [private]
Definition at line 2400 of file schema.h.
schemaStack_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
internal::Stack<StateAllocator> rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_ [private]
stack to store the current path of schema (BaseSchemaType *)
Definition at line 2404 of file schema.h.
stateAllocator_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
StateAllocator* rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::stateAllocator_ [private]
Definition at line 2402 of file schema.h.
valid_
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
bool rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_ [private]
Definition at line 2410 of file schema.h.
The documentation for this class was generated from the following files:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/fwd.h
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/schema.h