rapidjson::internal::IValidationErrorHandler< SchemaType > Class Template Reference
#include <schema.h>
Public Types
typedef SchemaType::Ch Ch
typedef SchemaType::SValue SValue
Public Member Functions
virtual ~IValidationErrorHandler ()
virtual void NotMultipleOf (int64_t actual, const SValue &expected)=0
virtual void NotMultipleOf (uint64_t actual, const SValue &expected)=0
virtual void NotMultipleOf (double actual, const SValue &expected)=0
virtual void AboveMaximum (int64_t actual, const SValue &expected, bool exclusive)=0
virtual void AboveMaximum (uint64_t actual, const SValue &expected, bool exclusive)=0
virtual void AboveMaximum (double actual, const SValue &expected, bool exclusive)=0
virtual void BelowMinimum (int64_t actual, const SValue &expected, bool exclusive)=0
virtual void BelowMinimum (uint64_t actual, const SValue &expected, bool exclusive)=0
virtual void BelowMinimum (double actual, const SValue &expected, bool exclusive)=0
virtual void TooLong (const Ch *str, SizeType length, SizeType expected)=0
virtual void TooShort (const Ch *str, SizeType length, SizeType expected)=0
virtual void DoesNotMatch (const Ch *str, SizeType length)=0
virtual void DisallowedItem (SizeType index)=0
virtual void TooFewItems (SizeType actualCount, SizeType expectedCount)=0
virtual void TooManyItems (SizeType actualCount, SizeType expectedCount)=0
virtual void DuplicateItems (SizeType index1, SizeType index2)=0
virtual void TooManyProperties (SizeType actualCount, SizeType expectedCount)=0
virtual void TooFewProperties (SizeType actualCount, SizeType expectedCount)=0
virtual void StartMissingProperties ()=0
virtual void AddMissingProperty (const SValue &name)=0
virtual bool EndMissingProperties ()=0
virtual void PropertyViolations (ISchemaValidator **subvalidators, SizeType count)=0
virtual void DisallowedProperty (const Ch *name, SizeType length)=0
virtual void StartDependencyErrors ()=0
virtual void StartMissingDependentProperties ()=0
virtual void AddMissingDependentProperty (const SValue &targetName)=0
virtual void EndMissingDependentProperties (const SValue &sourceName)=0
virtual void AddDependencySchemaError (const SValue &souceName, ISchemaValidator *subvalidator)=0
virtual bool EndDependencyErrors ()=0
virtual void DisallowedValue ()=0
virtual void StartDisallowedType ()=0
virtual void AddExpectedType (const typename SchemaType::ValueType &expectedType)=0
virtual void EndDisallowedType (const typename SchemaType::ValueType &actualType)=0
virtual void NotAllOf (ISchemaValidator **subvalidators, SizeType count)=0
virtual void NoneOf (ISchemaValidator **subvalidators, SizeType count)=0
virtual void NotOneOf (ISchemaValidator **subvalidators, SizeType count)=0
virtual void Disallowed ()=0
Detailed Description
template<typename SchemaType>
class rapidjson::internal::IValidationErrorHandler< SchemaType >
Definition at line 163 of file schema.h.
Member Typedef Documentation
Ch
template<typename SchemaType>
typedef SchemaType::Ch rapidjson::internal::IValidationErrorHandler< SchemaType >::Ch
Definition at line 165 of file schema.h.
SValue
template<typename SchemaType>
typedef SchemaType::SValue rapidjson::internal::IValidationErrorHandler< SchemaType >::SValue
Definition at line 166 of file schema.h.
Constructor & Destructor Documentation
 IValidationErrorHandler()
template<typename SchemaType>
virtual rapidjson::internal::IValidationErrorHandler< SchemaType >::~IValidationErrorHandler () [virtual]
Definition at line 168 of file schema.h.
{}
Member Function Documentation
AboveMaximum() [1/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AboveMaximum (int64_t actual, const SValue & expected, bool exclusive) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMaximum(), rapidjson::internal::Schema< SchemaDocumentType >::CheckInt(), and rapidjson::internal::Schema< SchemaDocumentType >::CheckUint().
AboveMaximum() [2/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AboveMaximum (uint64_t actual, const SValue & expected, bool exclusive) [pure virtual]
AboveMaximum() [3/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AboveMaximum (double actual, const SValue & expected, bool exclusive) [pure virtual]
AddDependencySchemaError()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AddDependencySchemaError (const SValue & souceName, ISchemaValidator * subvalidator) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
AddExpectedType()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AddExpectedType (const typename SchemaType::ValueType & expectedType) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::DisallowedType().
AddMissingDependentProperty()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AddMissingDependentProperty (const SValue & targetName) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
AddMissingProperty()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::AddMissingProperty (const SValue & name) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
BelowMinimum() [1/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::BelowMinimum (int64_t actual, const SValue & expected, bool exclusive) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMinimum(), rapidjson::internal::Schema< SchemaDocumentType >::CheckInt(), and rapidjson::internal::Schema< SchemaDocumentType >::CheckUint().
BelowMinimum() [2/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::BelowMinimum (uint64_t actual, const SValue & expected, bool exclusive) [pure virtual]
BelowMinimum() [3/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::BelowMinimum (double actual, const SValue & expected, bool exclusive) [pure virtual]
Disallowed()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::Disallowed () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
DisallowedItem()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedItem (SizeType index) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::BeginValue().
DisallowedProperty()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedProperty (const Ch * name, SizeType length) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::Key().
DisallowedValue()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::DisallowedValue () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
DoesNotMatch()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::DoesNotMatch (const Ch * str, SizeType length) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::String().
DuplicateItems()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::DuplicateItems (SizeType index1, SizeType index2) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
EndDependencyErrors()
template<typename SchemaType>
virtual bool rapidjson::internal::IValidationErrorHandler< SchemaType >::EndDependencyErrors () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
EndDisallowedType()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::EndDisallowedType (const typename SchemaType::ValueType & actualType) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::DisallowedType().
EndMissingDependentProperties()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::EndMissingDependentProperties (const SValue & sourceName) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
EndMissingProperties()
template<typename SchemaType>
virtual bool rapidjson::internal::IValidationErrorHandler< SchemaType >::EndMissingProperties () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
NoneOf()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::NoneOf (ISchemaValidator ** subvalidators, SizeType count) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
NotAllOf()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::NotAllOf (ISchemaValidator ** subvalidators, SizeType count) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
NotMultipleOf() [1/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::NotMultipleOf (int64_t actual, const SValue & expected) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf(), rapidjson::internal::Schema< SchemaDocumentType >::CheckInt(), and rapidjson::internal::Schema< SchemaDocumentType >::CheckUint().
NotMultipleOf() [2/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::NotMultipleOf (uint64_t actual, const SValue & expected) [pure virtual]
NotMultipleOf() [3/3]
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::NotMultipleOf (double actual, const SValue & expected) [pure virtual]
NotOneOf()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::NotOneOf (ISchemaValidator ** subvalidators, SizeType count) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
PropertyViolations()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::PropertyViolations (ISchemaValidator ** subvalidators, SizeType count) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
StartDependencyErrors()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::StartDependencyErrors () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
StartDisallowedType()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::StartDisallowedType () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::DisallowedType().
StartMissingDependentProperties()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::StartMissingDependentProperties () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
StartMissingProperties()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::StartMissingProperties () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
TooFewItems()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::TooFewItems (SizeType actualCount, SizeType expectedCount) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndArray().
TooFewProperties()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::TooFewProperties (SizeType actualCount, SizeType expectedCount) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
TooLong()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::TooLong (const Ch * str, SizeType length, SizeType expected) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::String().
TooManyItems()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::TooManyItems (SizeType actualCount, SizeType expectedCount) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndArray().
TooManyProperties()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::TooManyProperties (SizeType actualCount, SizeType expectedCount) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndObject().
TooShort()
template<typename SchemaType>
virtual void rapidjson::internal::IValidationErrorHandler< SchemaType >::TooShort (const Ch * str, SizeType length, SizeType expected) [pure virtual]
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::String().
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/schema.h