rapidjson::internal::Stack< Allocator > Class Template Reference
A type-unsafe stack for storing different types of data.
#include <stack.h>
Public Member Functions
Stack (Allocator *allocator, size_t stackCapacity)
~Stack ()
void Swap (Stack &rhs) RAPIDJSON_NOEXCEPT
void Clear ()
void ShrinkToFit ()
template<typename T >
RAPIDJSON_FORCEINLINE void Reserve (size_t count=1)
template<typename T >
RAPIDJSON_FORCEINLINE T * Push (size_t count=1)
template<typename T >
RAPIDJSON_FORCEINLINE T * PushUnsafe (size_t count=1)
template<typename T >
T * Pop (size_t count)
template<typename T >
T * Top ()
template<typename T >
const T * Top () const
template<typename T >
T * End ()
template<typename T >
const T * End () const
template<typename T >
T * Bottom ()
template<typename T >
const T * Bottom () const
bool HasAllocator () const
Allocator & GetAllocator ()
bool Empty () const
size_t GetSize () const
size_t GetCapacity () const
Private Member Functions
template<typename T >
void Expand (size_t count)
void Resize (size_t newCapacity)
void Destroy ()
Stack (const Stack &)
Stack & operator= (const Stack &)
Private Attributes
Allocator * allocator_
Allocator * ownAllocator_
char * stack_
char * stackTop_
char * stackEnd_
size_t initialCapacity_
Detailed Description
template<typename Allocator>
class rapidjson::internal::Stack< Allocator >
A type-unsafe stack for storing different types of data.
Template Parameters
Allocator Allocator for allocating stack memory.
Definition at line 37 of file stack.h.
Constructor & Destructor Documentation
Stack() [1/2]
template<typename Allocator>
rapidjson::internal::Stack< Allocator >::Stack (Allocator * allocator, size_t stackCapacity)
Definition at line 41 of file stack.h.
                                                      : allocator_(allocator), ownAllocator_(0), stack_(0), stackTop_(0), stackEnd_(0), initialCapacity_(stackCapacity) {
    }
 Stack()
template<typename Allocator>
rapidjson::internal::Stack< Allocator >::~Stack ()
Definition at line 62 of file stack.h.
             {
        Destroy();
    }
Stack() [2/2]
template<typename Allocator>
rapidjson::internal::Stack< Allocator >::Stack (const Stack< Allocator > &) [private]
Member Function Documentation
Bottom() [1/2]
template<typename Allocator>
template<typename T >
T* rapidjson::internal::Stack< Allocator >::Bottom ()
Definition at line 163 of file stack.h.
{ return reinterpret_cast<T*>(stack_); }
Bottom() [2/2]
template<typename Allocator>
template<typename T >
const T* rapidjson::internal::Stack< Allocator >::Bottom () const
Definition at line 166 of file stack.h.
{ return reinterpret_cast<T*>(stack_); }
Clear()
template<typename Allocator>
void rapidjson::internal::Stack< Allocator >::Clear ()
Definition at line 99 of file stack.h.
{ stackTop_ = stack_; }
Destroy()
template<typename Allocator>
void rapidjson::internal::Stack< Allocator >::Destroy () [private]
Definition at line 208 of file stack.h.
                   {
        Allocator::Free(stack_);
        RAPIDJSON_DELETE(ownAllocator_); // Only delete if it is owned by the stack
    }
Empty()
template<typename Allocator>
bool rapidjson::internal::Stack< Allocator >::Empty () const
Definition at line 177 of file stack.h.
{ return stackTop_ == stack_; }
Referenced by rapidjson::internal::GenericRegex< Encoding, Allocator >::Parse(), and rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::SearchWithAnchoring().
End() [1/2]
template<typename Allocator>
template<typename T >
T* rapidjson::internal::Stack< Allocator >::End ()
Definition at line 157 of file stack.h.
{ return reinterpret_cast<T*>(stackTop_); }
End() [2/2]
template<typename Allocator>
template<typename T >
const T* rapidjson::internal::Stack< Allocator >::End () const
Definition at line 160 of file stack.h.
{ return reinterpret_cast<T*>(stackTop_); }
Expand()
template<typename Allocator>
template<typename T >
void rapidjson::internal::Stack< Allocator >::Expand (size_t count) [private]
Definition at line 183 of file stack.h.
                              {
        // Only expand the capacity if the current stack exists. Otherwise just create a stack with initial capacity.
        size_t newCapacity;
        if (stack_ == 0) {
            if (!allocator_)
                ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
            newCapacity = initialCapacity_;
        } else {
            newCapacity = GetCapacity();
            newCapacity += (newCapacity + 1) / 2;
        }
        size_t newSize = GetSize() + sizeof(T) * count;
        if (newCapacity < newSize)
            newCapacity = newSize;
        Resize(newCapacity);
    }
GetAllocator()
template<typename Allocator>
Allocator& rapidjson::internal::Stack< Allocator >::GetAllocator ()
Definition at line 172 of file stack.h.
                              {
        RAPIDJSON_ASSERT(allocator_);
        return *allocator_;
    }
GetCapacity()
template<typename Allocator>
size_t rapidjson::internal::Stack< Allocator >::GetCapacity () const
Definition at line 179 of file stack.h.
{ return static_cast<size_t>(stackEnd_ - stack_); }
GetSize()
template<typename Allocator>
size_t rapidjson::internal::Stack< Allocator >::GetSize () const
Definition at line 178 of file stack.h.
{ return static_cast<size_t>(stackTop_ - stack_); }
Referenced by rapidjson::internal::GenericRegex< Encoding, Allocator >::Eval(), rapidjson::internal::GenericRegex< Encoding, Allocator >::EvalQuantifier(), and rapidjson::internal::GenericRegex< Encoding, Allocator >::Parse().
HasAllocator()
template<typename Allocator>
bool rapidjson::internal::Stack< Allocator >::HasAllocator () const
Definition at line 168 of file stack.h.
                              {
        return allocator_ != 0;
    }
operator=()
template<typename Allocator>
Stack& rapidjson::internal::Stack< Allocator >::operator= (const Stack< Allocator > &) [private]
Pop()
template<typename Allocator>
template<typename T >
T* rapidjson::internal::Stack< Allocator >::Pop (size_t count)
Definition at line 138 of file stack.h.
                         {
        RAPIDJSON_ASSERT(GetSize() >= count * sizeof(T));
        stackTop_ -= count * sizeof(T);
        return reinterpret_cast<T*>(stackTop_);
    }
Push()
template<typename Allocator>
template<typename T >
RAPIDJSON_FORCEINLINE T* rapidjson::internal::Stack< Allocator >::Push (size_t count = 1)
Definition at line 123 of file stack.h.
                                                    {
        Reserve<T>(count);
        return PushUnsafe<T>(count);
    }
PushUnsafe()
template<typename Allocator>
template<typename T >
RAPIDJSON_FORCEINLINE T* rapidjson::internal::Stack< Allocator >::PushUnsafe (size_t count = 1)
Definition at line 129 of file stack.h.
                                                          {
        RAPIDJSON_ASSERT(stackTop_);
        RAPIDJSON_ASSERT(static_cast<std::ptrdiff_t>(sizeof(T) * count) <= (stackEnd_ - stackTop_));
        T* ret = reinterpret_cast<T*>(stackTop_);
        stackTop_ += sizeof(T) * count;
        return ret;
    }
Reserve()
template<typename Allocator>
template<typename T >
RAPIDJSON_FORCEINLINE void rapidjson::internal::Stack< Allocator >::Reserve (size_t count = 1)
Definition at line 116 of file stack.h.
                                                         {
         // Expand the stack if needed
        if (RAPIDJSON_UNLIKELY(static_cast<std::ptrdiff_t>(sizeof(T) * count) > (stackEnd_ - stackTop_)))
            Expand<T>(count);
    }
Resize()
template<typename Allocator>
void rapidjson::internal::Stack< Allocator >::Resize (size_t newCapacity) [private]
Definition at line 201 of file stack.h.
                                    {
        const size_t size = GetSize(); // Backup the current size
        stack_ = static_cast<char*>(allocator_->Realloc(stack_, GetCapacity(), newCapacity));
        stackTop_ = stack_ + size;
        stackEnd_ = stack_ + newCapacity;
    }
ShrinkToFit()
template<typename Allocator>
void rapidjson::internal::Stack< Allocator >::ShrinkToFit ()
Definition at line 101 of file stack.h.
                       {
        if (Empty()) {
            // If the stack is empty, completely deallocate the memory.
            Allocator::Free(stack_); // NOLINT (+clang-analyzer-unix.Malloc)
            stack_ = 0;
            stackTop_ = 0;
            stackEnd_ = 0;
        }
        else
            Resize(GetSize());
    }
Swap()
template<typename Allocator>
void rapidjson::internal::Stack< Allocator >::Swap (Stack< Allocator > & rhs)
Definition at line 90 of file stack.h.
                                             {
        internal::Swap(allocator_, rhs.allocator_);
        internal::Swap(ownAllocator_, rhs.ownAllocator_);
        internal::Swap(stack_, rhs.stack_);
        internal::Swap(stackTop_, rhs.stackTop_);
        internal::Swap(stackEnd_, rhs.stackEnd_);
        internal::Swap(initialCapacity_, rhs.initialCapacity_);
    }
Top() [1/2]
template<typename Allocator>
template<typename T >
T* rapidjson::internal::Stack< Allocator >::Top ()
Definition at line 145 of file stack.h.
             {
        RAPIDJSON_ASSERT(GetSize() >= sizeof(T));
        return reinterpret_cast<T*>(stackTop_ - sizeof(T));
    }
Top() [2/2]
template<typename Allocator>
template<typename T >
const T* rapidjson::internal::Stack< Allocator >::Top () const
Definition at line 151 of file stack.h.
                         {
        RAPIDJSON_ASSERT(GetSize() >= sizeof(T));
        return reinterpret_cast<T*>(stackTop_ - sizeof(T));
    }
Field Documentation
allocator_
template<typename Allocator>
Allocator* rapidjson::internal::Stack< Allocator >::allocator_ [private]
Definition at line 217 of file stack.h.
initialCapacity_
template<typename Allocator>
size_t rapidjson::internal::Stack< Allocator >::initialCapacity_ [private]
Definition at line 222 of file stack.h.
ownAllocator_
template<typename Allocator>
Allocator* rapidjson::internal::Stack< Allocator >::ownAllocator_ [private]
Definition at line 218 of file stack.h.
stack_
template<typename Allocator>
char* rapidjson::internal::Stack< Allocator >::stack_ [private]
Definition at line 219 of file stack.h.
stackEnd_
template<typename Allocator>
char* rapidjson::internal::Stack< Allocator >::stackEnd_ [private]
Definition at line 221 of file stack.h.
stackTop_
template<typename Allocator>
char* rapidjson::internal::Stack< Allocator >::stackTop_ [private]
Definition at line 220 of file stack.h.
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/internal/stack.h