rapidjson::GenericPointer< ValueType, Allocator > Class Template Reference
Represents a JSON Pointer. Use Pointer for UTF8 encoding and default allocator.
#include <fwd.h>
Data Structures
class PercentEncodeStream
A helper stream to encode character (UTF-8 code unit) into percent-encoded sequence.
struct Token
A token is the basic units of internal representation.
Public Types
typedef ValueType::EncodingType EncodingType
Encoding type from Value.
typedef ValueType::Ch Ch
Character type from Value.
Public Member Functions
 Append token
GenericPointer Append (const Token &token, Allocator *allocator=0) const
Append a token and return a new Pointer.
GenericPointer Append (const Ch *name, SizeType length, Allocator *allocator=0) const
Append a name token with length, and return a new Pointer.
template<typename T >
RAPIDJSON_DISABLEIF_RETURN ((internal::NotExpr< internal::IsSame< typename internal::RemoveConst< T >::Type, Ch > >),(GenericPointer)) Append(T *name
Append a name token without length, and return a new Pointer.
Data Fields
Allocator * allocator
Allocator * allocator_
The current allocator. It is either user-supplied or equal to ownAllocator_.
Allocator * ownAllocator_
Allocator owned by this Pointer.
Ch * nameBuffer_
A buffer containing all names in tokens.
Token * tokens_
A list of tokens.
size_t tokenCount_
Number of tokens in tokens_.
size_t parseErrorOffset_
Offset in code unit when parsing fail.
PointerParseErrorCode parseErrorCode_
Parsing error code.
Constructors and destructor.
GenericPointer (Allocator *allocator=0)
Default constructor.
GenericPointer (const Ch *source, Allocator *allocator=0)
Constructor that parses a string or URI fragment representation.
GenericPointer (const Ch *source, size_t length, Allocator *allocator=0)
Constructor that parses a string or URI fragment representation, with length of the source string.
GenericPointer (const Token *tokens, size_t tokenCount)
Constructor with user-supplied tokens.
GenericPointer (const GenericPointer &rhs)
Copy constructor.
GenericPointer (const GenericPointer &rhs, Allocator *allocator)
Copy constructor.
~GenericPointer ()
Destructor.
GenericPointer & operator= (const GenericPointer &rhs)
Assignment operator.
GenericPointer & Swap (GenericPointer &other) RAPIDJSON_NOEXCEPT
Swap the content of this pointer with an other.
void swap (GenericPointer &a, GenericPointer &b) RAPIDJSON_NOEXCEPT
free-standing swap function helper
Detailed Description
template<typename ValueType, typename Allocator = CrtAllocator>
class rapidjson::GenericPointer< ValueType, Allocator >
Represents a JSON Pointer. Use Pointer for UTF8 encoding and default allocator.
This class implements RFC 6901 `JavaScript Object Notation (JSON) Pointer` (https://tools.ietf.org/html/rfc6901).
A JSON pointer is for identifying a specific value in a JSON document (GenericDocument). It can simplify coding of DOM tree manipulation, because it can access multiple-level depth of DOM tree with single API call.
After it parses a string representation (e.g. `/foo/0` or URI fragment representation (e.g. `#/foo/0`) into its internal representation (tokens), it can be used to resolve a specific value in multiple documents, or sub-tree of documents.
Contrary to GenericValue, Pointer can be copy constructed and copy assigned. Apart from assignment, a Pointer cannot be modified after construction.
Although Pointer is very convenient, please aware that constructing Pointer involves parsing and dynamic memory allocation. A special constructor with user- supplied tokens eliminates these.
GenericPointer depends on GenericDocument and GenericValue.
Template Parameters
ValueType The value type of the DOM tree. E.g. GenericValue<UTF8<> >
Allocator The allocator type for allocating memory for internal representation.
Note
GenericPointer uses same encoding of ValueType. However, Allocator of GenericPointer is independent of Allocator of Value.
Definition at line 126 of file fwd.h.
Member Typedef Documentation
Ch
template<typename ValueType , typename Allocator = CrtAllocator>
typedef ValueType::Ch rapidjson::GenericPointer< ValueType, Allocator >::Ch
Character type from Value.
Definition at line 82 of file pointer.h.
EncodingType
template<typename ValueType , typename Allocator = CrtAllocator>
typedef ValueType::EncodingType rapidjson::GenericPointer< ValueType, Allocator >::EncodingType
Encoding type from Value.
Definition at line 81 of file pointer.h.
Constructor & Destructor Documentation
GenericPointer() [1/6]
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer (Allocator * allocator = 0)
Default constructor.
Definition at line 107 of file pointer.h.
: allocator_(allocator), ownAllocator_(), nameBuffer_(), tokens_(), tokenCount_(), parseErrorOffset_(), parseErrorCode_(kPointerParseErrorNone) {}
GenericPointer() [2/6]
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer (const Ch * source, Allocator * allocator = 0) [explicit]
Constructor that parses a string or URI fragment representation.
Parameters
source A null-terminated, string or URI fragment representation of JSON pointer.
allocator User supplied allocator for this pointer. If no allocator is provided, it creates a self-owned one.
Definition at line 114 of file pointer.h.
                                                                        : allocator_(allocator), ownAllocator_(), nameBuffer_(), tokens_(), tokenCount_(), parseErrorOffset_(), parseErrorCode_(kPointerParseErrorNone) {
        Parse(source, internal::StrLen(source));
    }
References rapidjson::source, and rapidjson::internal::StrLen().
GenericPointer() [3/6]
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer (const Ch * source, size_t length, Allocator * allocator = 0)
Constructor that parses a string or URI fragment representation, with length of the source string.
Parameters
source A string or URI fragment representation of JSON pointer.
length Length of source.
allocator User supplied allocator for this pointer. If no allocator is provided, it creates a self-owned one.
Note
Slightly faster than the overload without length.
Definition at line 137 of file pointer.h.
                                                                              : allocator_(allocator), ownAllocator_(), nameBuffer_(), tokens_(), tokenCount_(), parseErrorOffset_(), parseErrorCode_(kPointerParseErrorNone) {
        Parse(source, length);
    }
References rapidjson::source.
GenericPointer() [4/6]
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer (const Token * tokens, size_t tokenCount)
Constructor with user-supplied tokens.
This constructor let user supplies const array of tokens. This prevents the parsing process and eliminates allocation. This is preferred for memory constrained environments.
Parameters
tokens An constant array of tokens representing the JSON pointer.
tokenCount Number of tokens.
Example
#define NAME(s) { s, sizeof(s) / sizeof(s[0]) - 1, kPointerInvalidIndex }
#define INDEX(i) { #i, sizeof(#i) - 1, i }
static const Pointer::Token kTokens[] = { NAME("foo"), INDEX(123) };
static const Pointer p(kTokens, sizeof(kTokens) / sizeof(kTokens[0]));
// Equivalent to static const Pointer p("/foo/123");
#undef NAME
#undef INDEX
Definition at line 163 of file pointer.h.
: allocator_(), ownAllocator_(), nameBuffer_(), tokens_(const_cast<Token*>(tokens)), tokenCount_(tokenCount), parseErrorOffset_(), parseErrorCode_(kPointerParseErrorNone) {}
GenericPointer() [5/6]
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer (const GenericPointer< ValueType, Allocator > & rhs)
Copy constructor.
Definition at line 166 of file pointer.h.
                                              : allocator_(rhs.allocator_), ownAllocator_(), nameBuffer_(), tokens_(), tokenCount_(), parseErrorOffset_(), parseErrorCode_(kPointerParseErrorNone) {
        *this = rhs;
    }
GenericPointer() [6/6]
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer (const GenericPointer< ValueType, Allocator > & rhs, Allocator * allocator)
Copy constructor.
Definition at line 171 of file pointer.h.
                                                                    : allocator_(allocator), ownAllocator_(), nameBuffer_(), tokens_(), tokenCount_(), parseErrorOffset_(), parseErrorCode_(kPointerParseErrorNone) {
        *this = rhs;
    }
 GenericPointer()
template<typename ValueType , typename Allocator = CrtAllocator>
rapidjson::GenericPointer< ValueType, Allocator >::~GenericPointer ()
Destructor.
Definition at line 176 of file pointer.h.
                      {
        if (nameBuffer_) // If user-supplied tokens constructor is used, nameBuffer_ is nullptr and tokens_ are not deallocated.
            Allocator::Free(tokens_);
        RAPIDJSON_DELETE(ownAllocator_);
    }
References RAPIDJSON_DELETE.
Member Function Documentation
Append() [1/2]
template<typename ValueType , typename Allocator = CrtAllocator>
GenericPointer rapidjson::GenericPointer< ValueType, Allocator >::Append (const Token & token, Allocator * allocator = 0) const
Append a token and return a new Pointer.
Parameters
token Token to be appended.
allocator Allocator for the newly return Pointer.
Returns
A new Pointer with appended token.
Definition at line 244 of file pointer.h.
                                                                              {
        GenericPointer r;
        r.allocator_ = allocator;
        Ch *p = r.CopyFromRaw(*this, 1, token.length + 1);
        std::memcpy(p, token.name, (token.length + 1) * sizeof(Ch));
        r.tokens_[tokenCount_].name = p;
        r.tokens_[tokenCount_].length = token.length;
        r.tokens_[tokenCount_].index = token.index;
        return r;
    }
References rapidjson::GenericPointer< ValueType, Allocator >::Token::index, rapidjson::GenericPointer< ValueType, Allocator >::Token::length, and rapidjson::GenericPointer< ValueType, Allocator >::Token::name.
Append() [2/2]
template<typename ValueType , typename Allocator = CrtAllocator>
GenericPointer rapidjson::GenericPointer< ValueType, Allocator >::Append (const Ch * name, SizeType length, Allocator * allocator = 0) const
Append a name token with length, and return a new Pointer.
Parameters
name Name to be appended.
length Length of name.
allocator Allocator for the newly return Pointer.
Returns
A new Pointer with appended token.
Definition at line 262 of file pointer.h.
                                                                                           {
        Token token = { name, length, kPointerInvalidIndex };
        return Append(token, allocator);
    }
References rapidjson::kPointerInvalidIndex.
operator=()
template<typename ValueType , typename Allocator = CrtAllocator>
GenericPointer& rapidjson::GenericPointer< ValueType, Allocator >::operator= (const GenericPointer< ValueType, Allocator > & rhs)
Assignment operator.
Definition at line 183 of file pointer.h.
                                                         {
        if (this != &rhs) {
            // Do not delete ownAllcator
            if (nameBuffer_)
                Allocator::Free(tokens_);
            tokenCount_ = rhs.tokenCount_;
            parseErrorOffset_ = rhs.parseErrorOffset_;
            parseErrorCode_ = rhs.parseErrorCode_;
            if (rhs.nameBuffer_)
                CopyFromRaw(rhs); // Normally parsed tokens.
            else {
                tokens_ = rhs.tokens_; // User supplied const tokens.
                nameBuffer_ = 0;
            }
        }
        return *this;
    }
RAPIDJSON_DISABLEIF_RETURN()
template<typename ValueType , typename Allocator = CrtAllocator>
template<typename T >
rapidjson::GenericPointer< ValueType, Allocator >::RAPIDJSON_DISABLEIF_RETURN ((internal::NotExpr< internal::IsSame< typename internal::RemoveConst< T >::Type, Ch > >) , (GenericPointer< ValueType, Allocator >))
Append a name token without length, and return a new Pointer.
Parameters
name Name (const Ch*) to be appended.
allocator Allocator for the newly return Pointer.
Returns
A new Pointer with appended token.
Swap()
template<typename ValueType , typename Allocator = CrtAllocator>
GenericPointer& rapidjson::GenericPointer< ValueType, Allocator >::Swap (GenericPointer< ValueType, Allocator > & other)
Swap the content of this pointer with an other.
Parameters
other The pointer to swap with.
Note
Constant complexity.
Definition at line 208 of file pointer.h.
                                                                   {
        internal::Swap(allocator_, other.allocator_);
        internal::Swap(ownAllocator_, other.ownAllocator_);
        internal::Swap(nameBuffer_, other.nameBuffer_);
        internal::Swap(tokens_, other.tokens_);
        internal::Swap(tokenCount_, other.tokenCount_);
        internal::Swap(parseErrorOffset_, other.parseErrorOffset_);
        internal::Swap(parseErrorCode_, other.parseErrorCode_);
        return *this;
    }
References rapidjson::internal::Swap().
Referenced by rapidjson::SwapValueByPointer().
Friends And Related Function Documentation
swap
template<typename ValueType , typename Allocator = CrtAllocator>
void swap (GenericPointer< ValueType, Allocator > & a, GenericPointer< ValueType, Allocator > & b) [friend]
free-standing swap function helper
Helper function to enable support for common swap implementation pattern based on std::swap:
void swap(MyClass& a, MyClass& b) {
    using std::swap;
    swap(a.pointer, b.pointer);
    // ...
}
See also
Swap()
Definition at line 231 of file pointer.h.
{ a.Swap(b); }
Field Documentation
allocator
template<typename ValueType , typename Allocator = CrtAllocator>
Allocator* rapidjson::GenericPointer< ValueType, Allocator >::allocator
Definition at line 275 of file pointer.h.
allocator_
template<typename ValueType , typename Allocator = CrtAllocator>
Allocator* rapidjson::GenericPointer< ValueType, Allocator >::allocator_
The current allocator. It is either user-supplied or equal to ownAllocator_.
Definition at line 1099 of file pointer.h.
nameBuffer_
template<typename ValueType , typename Allocator = CrtAllocator>
Ch* rapidjson::GenericPointer< ValueType, Allocator >::nameBuffer_
A buffer containing all names in tokens.
Definition at line 1101 of file pointer.h.
ownAllocator_
template<typename ValueType , typename Allocator = CrtAllocator>
Allocator* rapidjson::GenericPointer< ValueType, Allocator >::ownAllocator_
Allocator owned by this Pointer.
Definition at line 1100 of file pointer.h.
parseErrorCode_
template<typename ValueType , typename Allocator = CrtAllocator>
PointerParseErrorCode rapidjson::GenericPointer< ValueType, Allocator >::parseErrorCode_
Parsing error code.
Definition at line 1105 of file pointer.h.
parseErrorOffset_
template<typename ValueType , typename Allocator = CrtAllocator>
size_t rapidjson::GenericPointer< ValueType, Allocator >::parseErrorOffset_
Offset in code unit when parsing fail.
Definition at line 1104 of file pointer.h.
tokenCount_
template<typename ValueType , typename Allocator = CrtAllocator>
size_t rapidjson::GenericPointer< ValueType, Allocator >::tokenCount_
Number of tokens in tokens_.
Definition at line 1103 of file pointer.h.
tokens_
template<typename ValueType , typename Allocator = CrtAllocator>
Token* rapidjson::GenericPointer< ValueType, Allocator >::tokens_
A list of tokens.
Definition at line 1102 of file pointer.h.
The documentation for this class was generated from the following files:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/fwd.h
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/pointer.h