rapidjson::internal::GenericRegexSearch< RegexType, Allocator > Class Template Reference
#include <regex.h>
Public Types
typedef RegexType::EncodingType Encoding
typedef Encoding::Ch Ch
Public Member Functions
GenericRegexSearch (const RegexType &regex, Allocator *allocator=0)
~GenericRegexSearch ()
template<typename InputStream >
bool Match (InputStream &is)
bool Match (const Ch *s)
template<typename InputStream >
bool Search (InputStream &is)
bool Search (const Ch *s)
Private Types
typedef RegexType::State State
typedef RegexType::Range Range
Private Member Functions
template<typename InputStream >
bool SearchWithAnchoring (InputStream &is, bool anchorBegin, bool anchorEnd)
size_t GetStateSetSize () const
bool AddState (Stack< Allocator > &l, SizeType index)
bool MatchRange (SizeType rangeIndex, unsigned codepoint) const
Private Attributes
const RegexType & regex_
Allocator * allocator_
Allocator * ownAllocator_
Stack< Allocator > state0_
Stack< Allocator > state1_
uint32_t * stateSet_
Detailed Description
template<typename RegexType, typename Allocator = CrtAllocator>
class rapidjson::internal::GenericRegexSearch< RegexType, Allocator >
Definition at line 79 of file regex.h.
Member Typedef Documentation
Ch
template<typename RegexType, typename Allocator = CrtAllocator>
typedef Encoding::Ch rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Ch
Definition at line 610 of file regex.h.
Encoding
template<typename RegexType, typename Allocator = CrtAllocator>
typedef RegexType::EncodingType rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Encoding
Definition at line 609 of file regex.h.
Range
template<typename RegexType, typename Allocator = CrtAllocator>
typedef RegexType::Range rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Range [private]
Definition at line 651 of file regex.h.
State
template<typename RegexType, typename Allocator = CrtAllocator>
typedef RegexType::State rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::State [private]
Definition at line 650 of file regex.h.
Constructor & Destructor Documentation
GenericRegexSearch()
template<typename RegexType, typename Allocator = CrtAllocator>
rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::GenericRegexSearch (const RegexType & regex, Allocator * allocator = 0)
Definition at line 612 of file regex.h.
                                                                         :
        regex_(regex), allocator_(allocator), ownAllocator_(0),
        state0_(allocator, 0), state1_(allocator, 0), stateSet_()
    {
        RAPIDJSON_ASSERT(regex_.IsValid());
        if (!allocator_)
            ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
        stateSet_ = static_cast<unsigned*>(allocator_->Malloc(GetStateSetSize()));
        state0_.template Reserve<SizeType>(regex_.stateCount_);
        state1_.template Reserve<SizeType>(regex_.stateCount_);
    }
References RAPIDJSON_ASSERT, and RAPIDJSON_NEW.
 GenericRegexSearch()
template<typename RegexType, typename Allocator = CrtAllocator>
rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::~GenericRegexSearch ()
Definition at line 624 of file regex.h.
                          {
        Allocator::Free(stateSet_);
        RAPIDJSON_DELETE(ownAllocator_);
    }
References RAPIDJSON_DELETE.
Member Function Documentation
AddState()
template<typename RegexType, typename Allocator = CrtAllocator>
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::AddState (Stack< Allocator > & l, SizeType index) [private]
Definition at line 692 of file regex.h.
                                                       {
        RAPIDJSON_ASSERT(index != kRegexInvalidState);
        const State& s = regex_.GetState(index);
        if (s.out1 != kRegexInvalidState) { // Split
            bool matched = AddState(l, s.out);
            return AddState(l, s.out1) || matched;
        }
        else if (!(stateSet_[index >> 5] & (1u << (index & 31)))) {
            stateSet_[index >> 5] |= (1u << (index & 31));
            *l.template PushUnsafe<SizeType>() = index;
        }
        return s.out == kRegexInvalidState; // by using PushUnsafe() above, we can ensure s is not validated due to reallocation.
    }
References rapidjson::internal::kRegexInvalidState, and RAPIDJSON_ASSERT.
GetStateSetSize()
template<typename RegexType, typename Allocator = CrtAllocator>
size_t rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::GetStateSetSize () const [private]
Definition at line 687 of file regex.h.
                                   {
        return (regex_.stateCount_ + 31) / 32 * 4;
    }
Match() [1/2]
template<typename RegexType, typename Allocator = CrtAllocator>
template<typename InputStream >
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match (InputStream & is)
Definition at line 630 of file regex.h.
                                {
        return SearchWithAnchoring(is, true, true);
    }
Match() [2/2]
template<typename RegexType, typename Allocator = CrtAllocator>
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Match (const Ch * s)
Definition at line 634 of file regex.h.
                            {
        GenericStringStream<Encoding> is(s);
        return Match(is);
    }
MatchRange()
template<typename RegexType, typename Allocator = CrtAllocator>
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::MatchRange (SizeType rangeIndex, unsigned codepoint) const [private]
Definition at line 707 of file regex.h.
                                                                   {
        bool yes = (regex_.GetRange(rangeIndex).start & RegexType::kRangeNegationFlag) == 0;
        while (rangeIndex != kRegexInvalidRange) {
            const Range& r = regex_.GetRange(rangeIndex);
            if (codepoint >= (r.start & RegexType::kRangeNegationFlag) && codepoint <= r.end)
                return yes;
            rangeIndex = r.next;
        }
        return !yes;
    }
References rapidjson::internal::kRegexInvalidRange.
Search() [1/2]
template<typename RegexType, typename Allocator = CrtAllocator>
template<typename InputStream >
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search (InputStream & is)
Definition at line 640 of file regex.h.
                                 {
        return SearchWithAnchoring(is, regex_.anchorBegin_, regex_.anchorEnd_);
    }
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::IsPatternMatch().
Search() [2/2]
template<typename RegexType, typename Allocator = CrtAllocator>
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::Search (const Ch * s)
Definition at line 644 of file regex.h.
                             {
        GenericStringStream<Encoding> is(s);
        return Search(is);
    }
SearchWithAnchoring()
template<typename RegexType, typename Allocator = CrtAllocator>
template<typename InputStream >
bool rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::SearchWithAnchoring (InputStream & is, bool anchorBegin, bool anchorEnd) [private]
Definition at line 654 of file regex.h.
                                                                                {
        DecodedStream<InputStream, Encoding> ds(is);
        state0_.Clear();
        Stack<Allocator> *current = &state0_, *next = &state1_;
        const size_t stateSetSize = GetStateSetSize();
        std::memset(stateSet_, 0, stateSetSize);
        bool matched = AddState(*current, regex_.root_);
        unsigned codepoint;
        while (!current->Empty() && (codepoint = ds.Take()) != 0) {
            std::memset(stateSet_, 0, stateSetSize);
            next->Clear();
            matched = false;
            for (const SizeType* s = current->template Bottom<SizeType>(); s != current->template End<SizeType>(); ++s) {
                const State& sr = regex_.GetState(*s);
                if (sr.codepoint == codepoint ||
                    sr.codepoint == RegexType::kAnyCharacterClass ||
                    (sr.codepoint == RegexType::kRangeCharacterClass && MatchRange(sr.rangeStart, codepoint)))
                {
                    matched = AddState(*next, sr.out) || matched;
                    if (!anchorEnd && matched)
                        return true;
                }
                if (!anchorBegin)
                    AddState(*next, regex_.root_);
            }
            internal::Swap(current, next);
        }
        return matched;
    }
References rapidjson::internal::Stack< Allocator >::Empty(), rapidjson::internal::Swap(), and rapidjson::internal::DecodedStream< SourceStream, Encoding >::Take().
Field Documentation
allocator_
template<typename RegexType, typename Allocator = CrtAllocator>
Allocator* rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::allocator_ [private]
Definition at line 719 of file regex.h.
ownAllocator_
template<typename RegexType, typename Allocator = CrtAllocator>
Allocator* rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::ownAllocator_ [private]
Definition at line 720 of file regex.h.
regex_
template<typename RegexType, typename Allocator = CrtAllocator>
const RegexType& rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::regex_ [private]
Definition at line 718 of file regex.h.
state0_
template<typename RegexType, typename Allocator = CrtAllocator>
Stack<Allocator> rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::state0_ [private]
Definition at line 721 of file regex.h.
state1_
template<typename RegexType, typename Allocator = CrtAllocator>
Stack<Allocator> rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::state1_ [private]
Definition at line 722 of file regex.h.
stateSet_
template<typename RegexType, typename Allocator = CrtAllocator>
uint32_t* rapidjson::internal::GenericRegexSearch< RegexType, Allocator >::stateSet_ [private]
Definition at line 723 of file regex.h.
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/internal/regex.h