rapidjson::internal::Double Class Reference
#include <ieee754.h>
Public Member Functions
Double ()
Double (double d)
Double (uint64_t u)
double Value () const
uint64_t Uint64Value () const
double NextPositiveDouble () const
bool Sign () const
uint64_t Significand () const
int Exponent () const
bool IsNan () const
bool IsInf () const
bool IsNanOrInf () const
bool IsNormal () const
bool IsZero () const
uint64_t IntegerSignificand () const
int IntegerExponent () const
uint64_t ToBias () const
Static Public Member Functions
static int EffectiveSignificandSize (int order)
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 double d_
 uint64_t u_
};
Static Private Attributes
static const int kSignificandSize = 52
static const int kExponentBias = 0x3FF
static const int kDenormalExponent = 1 - kExponentBias
static const uint64_t kSignMask = ((static_cast<uint64_t>(0x80000000) << 32) | static_cast<uint64_t>(0x00000000))
static const uint64_t kExponentMask = ((static_cast<uint64_t>(0x7FF00000) << 32) | static_cast<uint64_t>(0x00000000))
static const uint64_t kSignificandMask = ((static_cast<uint64_t>(0x000FFFFF) << 32) | static_cast<uint64_t>(0xFFFFFFFF))
static const uint64_t kHiddenBit = ((static_cast<uint64_t>(0x00100000) << 32) | static_cast<uint64_t>(0x00000000))
Detailed Description
Definition at line 23 of file ieee754.h.
Constructor & Destructor Documentation
Double() [1/3]
rapidjson::internal::Double::Double ()
Definition at line 25 of file ieee754.h.
{}
Double() [2/3]
rapidjson::internal::Double::Double (double d)
Definition at line 26 of file ieee754.h.
: d_(d) {}
Double() [3/3]
rapidjson::internal::Double::Double (uint64_t u)
Definition at line 27 of file ieee754.h.
: u_(u) {}
Member Function Documentation
EffectiveSignificandSize()
static int rapidjson::internal::Double::EffectiveSignificandSize (int order) [static]
Definition at line 51 of file ieee754.h.
                                                   {
        if (order >= -1021)
            return 53;
        else if (order <= -1074)
            return 0;
        else
            return order + 1074;
    }
Exponent()
int rapidjson::internal::Double::Exponent () const
Definition at line 39 of file ieee754.h.
{ return static_cast<int>(((u_ & kExponentMask) >> kSignificandSize) - kExponentBias); }
IntegerExponent()
int rapidjson::internal::Double::IntegerExponent () const
Definition at line 48 of file ieee754.h.
{ return (IsNormal() ? Exponent() : kDenormalExponent) - kSignificandSize; }
Referenced by rapidjson::internal::CheckWithinHalfULP().
IntegerSignificand()
uint64_t rapidjson::internal::Double::IntegerSignificand () const
Definition at line 47 of file ieee754.h.
{ return IsNormal() ? Significand() | kHiddenBit : Significand(); }
Referenced by rapidjson::internal::CheckWithinHalfULP().
IsInf()
bool rapidjson::internal::Double::IsInf () const
Definition at line 42 of file ieee754.h.
{ return (u_ & kExponentMask) == kExponentMask && Significand() == 0; }
IsNan()
bool rapidjson::internal::Double::IsNan () const
Definition at line 41 of file ieee754.h.
{ return (u_ & kExponentMask) == kExponentMask && Significand() != 0; }
IsNanOrInf()
bool rapidjson::internal::Double::IsNanOrInf () const
Definition at line 43 of file ieee754.h.
{ return (u_ & kExponentMask) == kExponentMask; }
IsNormal()
bool rapidjson::internal::Double::IsNormal () const
Definition at line 44 of file ieee754.h.
{ return (u_ & kExponentMask) != 0 || Significand() == 0; }
IsZero()
bool rapidjson::internal::Double::IsZero () const
Definition at line 45 of file ieee754.h.
{ return (u_ & (kExponentMask | kSignificandMask)) == 0; }
Referenced by rapidjson::internal::dtoa().
NextPositiveDouble()
double rapidjson::internal::Double::NextPositiveDouble () const
Definition at line 32 of file ieee754.h.
                                      {
        RAPIDJSON_ASSERT(!Sign());
        return Double(u_ + 1).Value();
    }
References RAPIDJSON_ASSERT, and Value().
Sign()
bool rapidjson::internal::Double::Sign () const
Definition at line 37 of file ieee754.h.
{ return (u_ & kSignMask) != 0; }
Referenced by rapidjson::internal::dtoa().
Significand()
uint64_t rapidjson::internal::Double::Significand () const
Definition at line 38 of file ieee754.h.
{ return u_ & kSignificandMask; }
ToBias()
uint64_t rapidjson::internal::Double::ToBias () const
Definition at line 49 of file ieee754.h.
{ return (u_ & kSignMask) ? u_ + 1 : u_ | kSignMask; }
Uint64Value()
uint64_t rapidjson::internal::Double::Uint64Value () const
Definition at line 30 of file ieee754.h.
{ return u_; }
Value()
double rapidjson::internal::Double::Value () const
Definition at line 29 of file ieee754.h.
{ return d_; }
Referenced by NextPositiveDouble().
Field Documentation
@8
union { ... } [private]
d_
double rapidjson::internal::Double::d_
Definition at line 70 of file ieee754.h.
kDenormalExponent
const int rapidjson::internal::Double::kDenormalExponent = 1 - kExponentBias [static], [private]
Definition at line 63 of file ieee754.h.
kExponentBias
const int rapidjson::internal::Double::kExponentBias = 0x3FF [static], [private]
Definition at line 62 of file ieee754.h.
kExponentMask
const uint64_t rapidjson::internal::Double::kExponentMask = ((static_cast<uint64_t>(0x7FF00000) << 32) | static_cast<uint64_t>(0x00000000)) [static], [private]
Definition at line 65 of file ieee754.h.
kHiddenBit
const uint64_t rapidjson::internal::Double::kHiddenBit = ((static_cast<uint64_t>(0x00100000) << 32) | static_cast<uint64_t>(0x00000000)) [static], [private]
Definition at line 67 of file ieee754.h.
kSignificandMask
const uint64_t rapidjson::internal::Double::kSignificandMask = ((static_cast<uint64_t>(0x000FFFFF) << 32) | static_cast<uint64_t>(0xFFFFFFFF)) [static], [private]
Definition at line 66 of file ieee754.h.
kSignificandSize
const int rapidjson::internal::Double::kSignificandSize = 52 [static], [private]
Definition at line 61 of file ieee754.h.
kSignMask
const uint64_t rapidjson::internal::Double::kSignMask = ((static_cast<uint64_t>(0x80000000) << 32) | static_cast<uint64_t>(0x00000000)) [static], [private]
Definition at line 64 of file ieee754.h.
u_
uint64_t rapidjson::internal::Double::u_
Definition at line 71 of file ieee754.h.
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/internal/ieee754.h