rapidjson::internal::ISchemaStateFactory< SchemaType > Class Template Reference
#include <schema.h>
Public Member Functions
virtual ~ISchemaStateFactory ()
virtual ISchemaValidator * CreateSchemaValidator (const SchemaType &)=0
virtual void DestroySchemaValidator (ISchemaValidator *validator)=0
virtual void * CreateHasher ()=0
virtual uint64_t GetHashCode (void *hasher)=0
virtual void DestroryHasher (void *hasher)=0
virtual void * MallocState (size_t size)=0
virtual void FreeState (void *p)=0
Detailed Description
template<typename SchemaType>
class rapidjson::internal::ISchemaStateFactory< SchemaType >
Definition at line 147 of file schema.h.
Constructor & Destructor Documentation
 ISchemaStateFactory()
template<typename SchemaType>
virtual rapidjson::internal::ISchemaStateFactory< SchemaType >::~ISchemaStateFactory () [virtual]
Definition at line 149 of file schema.h.
{}
Member Function Documentation
CreateHasher()
template<typename SchemaType>
virtual void* rapidjson::internal::ISchemaStateFactory< SchemaType >::CreateHasher () [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::CreateParallelValidator().
CreateSchemaValidator()
template<typename SchemaType>
virtual ISchemaValidator* rapidjson::internal::ISchemaStateFactory< SchemaType >::CreateSchemaValidator (const SchemaType &) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and rapidjson::internal::Schema< SchemaDocumentType >::CreateSchemaValidators().
DestroryHasher()
template<typename SchemaType>
virtual void rapidjson::internal::ISchemaStateFactory< SchemaType >::DestroryHasher (void * hasher) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
DestroySchemaValidator()
template<typename SchemaType>
virtual void rapidjson::internal::ISchemaStateFactory< SchemaType >::DestroySchemaValidator (ISchemaValidator * validator) [pure virtual]
FreeState()
template<typename SchemaType>
virtual void rapidjson::internal::ISchemaStateFactory< SchemaType >::FreeState (void * p) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
GetHashCode()
template<typename SchemaType>
virtual uint64_t rapidjson::internal::ISchemaStateFactory< SchemaType >::GetHashCode (void * hasher) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::EndValue().
MallocState()
template<typename SchemaType>
virtual void* rapidjson::internal::ISchemaStateFactory< SchemaType >::MallocState (size_t size) [pure virtual]
Implemented in rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and rapidjson::internal::Schema< SchemaDocumentType >::StartObject().
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/schema.h