Integration_algorithms Class Reference
#include <Integration_algorithms.h>
Public Member Functions
Integration_algorithms ()
~Integration_algorithms ()
void complementary_filter (double *angle, double acc)
Function to create a filtered version of the calculated change of rotation.
double Roll (double gyro_y, double acc_x, double acc_z)
Calculation of the roll (y-axis sensor rotation)
double Pitch (double gyro_x, double acc_y, double acc_z)
Calculation of the roll (x-axis sensor rotation)
int squat_straight_back (double gyro_y, double acc_x, double acc_z)
Algorithm checking for back rotation during squats.
int squat_twist_right_knee (double gyro_x, double acc_y, double acc_z)
Algorithm checking for twisting of the right knee.
int squat_twist_left_knee (double gyro_x, double acc_y, double acc_z)
Algorithm checking for twisting of the right knee.
int plank_bend_back (double gyro_y, double acc_x, double acc_z)
Algorithm checking for bent back during planks/push ups.
int pushup_shoulder_back (double s1_gyro_y, double s1_acc_x, double s1_acc_z, double s2_gyro_y, double s2_acc_x, double s2_acc_z)
Algorithm checking for rate of change between the back and the shoulders during push ups.
int pushup_knee_back (double s1_gyro_y, double s1_acc_x, double s1_acc_z, double s3_gyro_y, double s3_acc_x, double s3_acc_z)
Algorithm checking for rate of change between the back and the knees during push ups.
Private Attributes
Buffer * sensor1_rotx
Buffer * sensor1_roty
Buffer * sensor2_rotx
Buffer * sensor2_roty
Buffer * sensor3_rotx
Buffer * sensor3_roty
Detailed Description
Definition at line 13 of file Integration_algorithms.h.
Constructor & Destructor Documentation
Integration_algorithms()
Integration_algorithms::Integration_algorithms ()
Definition at line 20 of file Integration_algorithms.cpp.
                                              {
    sensor1_rotx = new Buffer();
    sensor1_roty = new Buffer();
    sensor2_rotx = new Buffer();
    sensor2_roty = new Buffer();
    sensor3_rotx = new Buffer();
    sensor3_roty = new Buffer();
}
 Integration_algorithms()
Integration_algorithms::~Integration_algorithms ()
Definition at line 29 of file Integration_algorithms.cpp.
                                               {
}
Member Function Documentation
complementary_filter()
void Integration_algorithms::complementary_filter (double * angle, double acc)
Function to create a filtered version of the calculated change of rotation.
Parameters
angle A pointer to the rotational angle
acc The acceleration used for the filtering
Definition at line 39 of file Integration_algorithms.cpp.
{
    *angle = ((double)0.98)*(*angle) + 0.02*acc;
}
Pitch()
double Integration_algorithms::Pitch (double gyro_x, double acc_y, double acc_z)
Calculation of the roll (x-axis sensor rotation)
Parameters
gyro_x The value from the x-axis of the gyroscope
acc_y The value from the y-axis of the accelerometer
acc_z The value from the z-axis of the accelerometer
Definition at line 69 of file Integration_algorithms.cpp.
{
    double pitch;
    double dt = 0.01;
    pitch += gyro_x * dt;
    double acc_correction_x = atan2f(acc_y, acc_z)*180/M_PI;
    if (acc_correction_x >180.0){
        acc_correction_x -=(double)360.0;
    }
    complementary_filter(&pitch, acc_correction_x);
    return pitch;
}
Referenced by squat_twist_left_knee(), and squat_twist_right_knee().
plank_bend_back()
int Integration_algorithms::plank_bend_back (double gyro_y, double acc_x, double acc_z)
Algorithm checking for bent back during planks/push ups.
Parameters
gyro_y The value from the sensor on the back for the y-axis of the gyroscope
acc_x The value from the sensor on the back for the x-axis of the accelerometer
acc_z The value from the sensor on the back for the z-axis of the accelerometer
Definition at line 145 of file Integration_algorithms.cpp.
{
    double Roll = Integration_algorithms::Roll(gyro_y, acc_x, acc_z);
    if (Roll > 0){
        return 6; //message "Straighten you back during exercise!"
    } else{
        return 7; //message "Keep the nice posture"
    }
}
References Roll().
pushup_knee_back()
int Integration_algorithms::pushup_knee_back (double s1_gyro_y, double s1_acc_x, double s1_acc_z, double s3_gyro_y, double s3_acc_x, double s3_acc_z)
Algorithm checking for rate of change between the back and the knees during push ups.
Parameters
s1_gyro_y The value from the sensor on the back for the y-axis of the gyroscope
s1_acc_x The value from the sensor on the back for the x-axis of the accelerometer
s1_acc_z The value from the sensor on the back for the z-axis of the accelerometer
s3_gyro_y The value from the sensor on the right knee for the y-axis of the gyroscope
s3_acc_x The value from the sensor on the right knee for the x-axis of the accelerometer
s3_acc_z The value from the sensor on the right knee for the z-axis of the accelerometer
Definition at line 190 of file Integration_algorithms.cpp.
{
    sensor1_roty->buffer(Integration_algorithms::Roll(s1_gyro_y, s1_acc_x, s1_acc_z)); //back sensor
    double* rotation1_x = sensor1_roty->get_buffer();
    sensor3_roty->buffer(Integration_algorithms::Roll(s3_gyro_y, s3_acc_x, s3_acc_z)); //knee sensor
    double* rotation3_x = sensor3_roty->get_buffer();
    if ((abs(rotation1_x[1] - rotation1_x[0]) - abs(rotation3_x[1] - rotation3_x[0])) > 0.2){
        cout<<"Dont bend your knees"<<endl;
        return 10;
    }{
        cout<<"right way"<<endl;
        return 11;
    }
}
References Roll().
pushup_shoulder_back()
int Integration_algorithms::pushup_shoulder_back (double s1_gyro_y, double s1_acc_x, double s1_acc_z, double s2_gyro_y, double s2_acc_x, double s2_acc_z)
Algorithm checking for rate of change between the back and the shoulders during push ups.
Parameters
s1_gyro_y The value from the sensor on the back for the y-axis of the gyroscope
s1_acc_x The value from the sensor on the back for the x-axis of the accelerometer
s1_acc_z The value from the sensor on the back for the z-axis of the accelerometer
s2_gyro_y The value from the sensor on the shoulders for the y-axis of the gyroscope
s2_acc_x The value from the sensor on the shoulders for the x-axis of the accelerometer
s2_acc_z The value from the sensor on the shoulders for the z-axis of the accelerometer
Definition at line 166 of file Integration_algorithms.cpp.
{
    sensor1_roty->buffer(Integration_algorithms::Roll(s1_gyro_y, s1_acc_x, s1_acc_z)); //back sensor
    double* rotation1_x = sensor1_roty->get_buffer();
    sensor2_roty->buffer(Integration_algorithms::Roll(s2_gyro_y, s2_acc_x, s2_acc_z)); //shoulder sensor
    double* rotation2_x = sensor2_roty->get_buffer();
    if ((abs(rotation1_x[1] - rotation1_x[0]) - abs(rotation2_x[1] - rotation2_x[0])) > 0.2){
        cout<<"Straighten your shoulders"<<endl;
        return 8;
    }{
        cout<<"right way"<<endl;
        return 9;
    }
}
References Roll().
Roll()
double Integration_algorithms::Roll (double gyro_y, double acc_x, double acc_z)
Calculation of the roll (y-axis sensor rotation)
Parameters
gyro_y The value from the y-axis of the gyroscope
acc_x The value from the x-axis of the accelerometer
acc_z The value from the z-axis of the accelerometer
Definition at line 51 of file Integration_algorithms.cpp.
{
    double roll;
    double dt = 0.01;
    roll += gyro_y * dt;
    double acc_correction_y = atan2f(acc_z, acc_x) *180/M_PI;
    complementary_filter(&roll, acc_correction_y);
    return roll;
}
Referenced by plank_bend_back(), pushup_knee_back(), pushup_shoulder_back(), and squat_straight_back().
squat_straight_back()
int Integration_algorithms::squat_straight_back (double gyro_y, double acc_x, double acc_z)
Algorithm checking for back rotation during squats.
Parameters
gyro_y The value from the sensor on the back the y-axis of the gyroscope
acc_x The value from the sensor on the back the x-axis of the accelerometer
acc_z The value from the sensor on the back the z-axis of the accelerometer
Definition at line 91 of file Integration_algorithms.cpp.
{
    double roll = Integration_algorithms::Roll(gyro_y, acc_x, acc_z);
    if (roll < 0.2 || roll > 0.2){
        return 1; //message "Bend during exercise!"
    } else{
        return 2; //message "Keep the nice posture"
    }
}
References Roll().
Referenced by parsing_function().
squat_twist_left_knee()
int Integration_algorithms::squat_twist_left_knee (double gyro_x, double acc_y, double acc_z)
Algorithm checking for twisting of the right knee.
Parameters
gyro_x The value from the sensor on the left knee for the x-axis of the gyroscope
acc_y The value from the sensor on the left knee for the y-axis of the accelerometer
acc_z The value from the sensor on the left knee for the z-axis of the accelerometer
Definition at line 127 of file Integration_algorithms.cpp.
{
    sensor2_rotx->buffer(Integration_algorithms::Pitch(gyro_x, acc_y, acc_z));
    double* rotation_x = sensor2_rotx->get_buffer();
    if (abs(rotation_x[1] - rotation_x[0]) > 0.3){
        return 4; //wrong way
    }{
        return 5; //right way
    }
}
References Pitch().
squat_twist_right_knee()
int Integration_algorithms::squat_twist_right_knee (double gyro_x, double acc_y, double acc_z)
Algorithm checking for twisting of the right knee.
Parameters
gyro_x The value from the sensor on the right knee for the x-axis of the gyroscope
acc_y The value from the sensor on the right knee for the y-axis of the accelerometer
acc_z The value from the sensor on the right knee for the z-axis of the accelerometer
Definition at line 109 of file Integration_algorithms.cpp.
{
    sensor1_rotx->buffer(Integration_algorithms::Pitch(gyro_x, acc_y, acc_z));
    double* rotation_x = sensor1_rotx->get_buffer();
    if (abs(rotation_x[1] - rotation_x[0]) > 0.3){
        return 3; //wrong way
    }{
        return 5; //right way
    }
}
References Pitch().
Field Documentation
sensor1_rotx
Buffer* Integration_algorithms::sensor1_rotx [private]
Definition at line 30 of file Integration_algorithms.h.
sensor1_roty
Buffer* Integration_algorithms::sensor1_roty [private]
Definition at line 31 of file Integration_algorithms.h.
sensor2_rotx
Buffer* Integration_algorithms::sensor2_rotx [private]
Definition at line 32 of file Integration_algorithms.h.
sensor2_roty
Buffer* Integration_algorithms::sensor2_roty [private]
Definition at line 33 of file Integration_algorithms.h.
sensor3_rotx
Buffer* Integration_algorithms::sensor3_rotx [private]
Definition at line 34 of file Integration_algorithms.h.
sensor3_roty
Buffer* Integration_algorithms::sensor3_roty [private]
Definition at line 35 of file Integration_algorithms.h.
The documentation for this class was generated from the following files:
D:/cloned repo trainawear/train-A-wear/Server/Integration_algorithms.h
D:/cloned repo trainawear/train-A-wear/Server/Integration_algorithms.cpp