rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator > Class Template Reference
A helper class for parsing with validation.
#include <schema.h>
Public Types
typedef SchemaDocumentType::PointerType PointerType
typedef InputStream::Ch Ch
typedef GenericValue< SourceEncoding, StackAllocator > ValueType
Public Member Functions
SchemaValidatingReader (InputStream &is, const SchemaDocumentType &sd)
Constructor.
template<typename Handler >
bool operator() (Handler &handler)
const ParseResult & GetParseResult () const
bool IsValid () const
const PointerType & GetInvalidSchemaPointer () const
const Ch * GetInvalidSchemaKeyword () const
const PointerType & GetInvalidDocumentPointer () const
const ValueType & GetError () const
Private Attributes
InputStream & is_
const SchemaDocumentType & sd_
ParseResult parseResult_
PointerType invalidSchemaPointer_
const Ch * invalidSchemaKeyword_
PointerType invalidDocumentPointer_
StackAllocator allocator_
ValueType error_
bool isValid_
Detailed Description
template<unsigned parseFlags, typename InputStream, typename SourceEncoding, typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
class rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >
A helper class for parsing with validation.
This helper class is a functor, designed as a parameter of GenericDocument::Populate().
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept.
SourceEncoding Encoding of the input stream.
SchemaDocumentType Type of schema document.
StackAllocator Allocator type for stack.
Definition at line 2437 of file schema.h.
Member Typedef Documentation
Ch
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
typedef InputStream::Ch rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::Ch
Definition at line 2440 of file schema.h.
PointerType
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
typedef SchemaDocumentType::PointerType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::PointerType
Definition at line 2439 of file schema.h.
ValueType
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
typedef GenericValue<SourceEncoding, StackAllocator> rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::ValueType
Definition at line 2441 of file schema.h.
Constructor & Destructor Documentation
SchemaValidatingReader()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::SchemaValidatingReader (InputStream & is, const SchemaDocumentType & sd)
Constructor.
Parameters
is Input stream.
sd Schema document.
Definition at line 2448 of file schema.h.
: is_(is), sd_(sd), invalidSchemaKeyword_(), error_(kObjectType), isValid_(true) {}
Member Function Documentation
GetError()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const ValueType& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetError () const
Definition at line 2478 of file schema.h.
{ return error_; }
GetInvalidDocumentPointer()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const PointerType& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidDocumentPointer () const
Definition at line 2477 of file schema.h.
{ return invalidDocumentPointer_; }
GetInvalidSchemaKeyword()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const Ch* rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaKeyword () const
Definition at line 2476 of file schema.h.
{ return invalidSchemaKeyword_; }
GetInvalidSchemaPointer()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const PointerType& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaPointer () const
Definition at line 2475 of file schema.h.
{ return invalidSchemaPointer_; }
GetParseResult()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const ParseResult& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetParseResult () const
Definition at line 2473 of file schema.h.
{ return parseResult_; }
IsValid()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
bool rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::IsValid () const
Definition at line 2474 of file schema.h.
{ return isValid_; }
operator()()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
template<typename Handler >
bool rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator() (Handler & handler)
Definition at line 2451 of file schema.h.
                                      {
        GenericReader<SourceEncoding, typename SchemaDocumentType::EncodingType, StackAllocator> reader;
        GenericSchemaValidator<SchemaDocumentType, Handler> validator(sd_, handler);
        parseResult_ = reader.template Parse<parseFlags>(is_, validator);
        isValid_ = validator.IsValid();
        if (isValid_) {
            invalidSchemaPointer_ = PointerType();
            invalidSchemaKeyword_ = 0;
            invalidDocumentPointer_ = PointerType();
            error_.SetObject();
        }
        else {
            invalidSchemaPointer_ = validator.GetInvalidSchemaPointer();
            invalidSchemaKeyword_ = validator.GetInvalidSchemaKeyword();
            invalidDocumentPointer_ = validator.GetInvalidDocumentPointer();
            error_.CopyFrom(validator.GetError(), allocator_);
        }
        return parseResult_;
    }
References rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer(), and rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid().
Field Documentation
allocator_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
StackAllocator rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::allocator_ [private]
Definition at line 2488 of file schema.h.
error_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
ValueType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::error_ [private]
Definition at line 2489 of file schema.h.
invalidDocumentPointer_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
PointerType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidDocumentPointer_ [private]
Definition at line 2487 of file schema.h.
invalidSchemaKeyword_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const Ch* rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidSchemaKeyword_ [private]
Definition at line 2486 of file schema.h.
invalidSchemaPointer_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
PointerType rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::invalidSchemaPointer_ [private]
Definition at line 2485 of file schema.h.
is_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
InputStream& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::is_ [private]
Definition at line 2481 of file schema.h.
isValid_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
bool rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::isValid_ [private]
Definition at line 2490 of file schema.h.
parseResult_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
ParseResult rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::parseResult_ [private]
Definition at line 2484 of file schema.h.
sd_
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
const SchemaDocumentType& rapidjson::SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::sd_ [private]
Definition at line 2482 of file schema.h.
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/schema.h