rapidjson Namespace Reference
main RapidJSON namespace
Namespaces
 internal
Data Structures
class Allocator
Concept for allocating, resizing and freeing memory block.
struct ASCII
ASCII encoding.
struct AutoUTF
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
class AutoUTFInputStream
Input stream wrapper with dynamically bound encoding and automatic encoding detection.
class AutoUTFOutputStream
Output stream wrapper with dynamically bound encoding and automatic encoding detection.
struct BaseReaderHandler
Default implementation of Handler.
class BasicIStreamWrapper
Wrapper of std::basic_istream into RapidJSON's Stream concept.
class BasicOStreamWrapper
Wrapper of std::basic_ostream into RapidJSON's Stream concept.
class CrtAllocator
C-runtime library allocator.
class CursorStreamWrapper
Cursor stream wrapper for counting line and column number if error exists.
class EncodedInputStream
Input byte stream wrapper with a statically bound encoding.
class EncodedInputStream< UTF8<>, MemoryStream >
Specialized for UTF8 MemoryStream.
class EncodedOutputStream
Output byte stream wrapper with statically bound encoding.
class Encoding
Concept for encoding of Unicode characters.
class FileReadStream
File byte stream for input using fread().
class FileWriteStream
Wrapper of C file stream for output using fwrite().
class GenericArray
Helper class for accessing Value of array type.
class GenericDocument
A document for parsing JSON text as DOM.
struct GenericInsituStringStream
A read-write string stream.
struct GenericMember
Name-value pair in a JSON object value.
class GenericMemberIterator
(Constant) member iterator for a JSON object value
struct GenericMemoryBuffer
Represents an in-memory output byte stream.
class GenericObject
Helper class for accessing Value of object type.
class GenericPointer
Represents a JSON Pointer. Use Pointer for UTF8 encoding and default allocator.
class GenericReader
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
class GenericSchemaDocument
JSON schema document.
class GenericSchemaValidator
JSON Schema Validator.
class GenericStreamWrapper
A Stream Wrapper.
class GenericStringBuffer
Represents an in-memory output stream.
struct GenericStringRef
Reference to a constant string (not taking a copy)
struct GenericStringStream
Read-only string stream.
class GenericValue
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
class Handler
Concept for receiving events from GenericReader upon parsing. The functions return true if no error occurs. If they return false, the event publisher should terminate the process.
class IGenericRemoteSchemaDocumentProvider
class MemoryPoolAllocator
Default memory allocator used by the parser and DOM.
struct MemoryStream
Represents an in-memory input byte stream.
struct ParseResult
Result of parsing (wraps ParseErrorCode)
class PrettyWriter
Writer with indentation and spacing.
class SchemaValidatingReader
A helper class for parsing with validation.
class Stream
Concept for reading and writing characters.
struct StreamTraits
Provides additional information for stream.
struct StreamTraits< GenericInsituStringStream< Encoding > >
struct StreamTraits< GenericStringStream< Encoding > >
struct Transcoder
Encoding conversion.
struct Transcoder< Encoding, Encoding >
Specialization of Transcoder with same source and target encoding.
struct UTF16
UTF-16 encoding.
struct UTF16BE
UTF-16 big endian encoding.
struct UTF16LE
UTF-16 little endian encoding.
struct UTF32
UTF-32 encoding.
struct UTF32BE
UTF-32 big endian encoding.
struct UTF32LE
UTF-32 little endian enocoding.
struct UTF8
UTF-8 encoding.
class Writer
JSON writer.
Typedefs
typedef GenericValue< UTF8<> > Value
GenericValue with UTF8 encoding.
typedef GenericDocument< UTF8<> > Document
GenericDocument with UTF8 encoding.
typedef const char *(* GetParseErrorFunc) (ParseErrorCode)
Function pointer type of GetParseError().
typedef GenericStringStream< UTF8< char > > StringStream
String stream with UTF8 encoding.
typedef GenericInsituStringStream< UTF8< char > > InsituStringStream
Insitu string stream with UTF8 encoding.
typedef GenericStringBuffer< UTF8< char >, CrtAllocator > StringBuffer
String buffer with UTF8 encoding.
typedef GenericMemoryBuffer< CrtAllocator > MemoryBuffer
typedef GenericReader< UTF8< char >, UTF8< char >, CrtAllocator > Reader
Reader with UTF8 encoding and default allocator.
typedef GenericPointer< Value, CrtAllocator > Pointer
GenericPointer for Value (UTF-8, default allocator).
typedef GenericSchemaDocument< Value, CrtAllocator > SchemaDocument
GenericSchemaDocument using Value type.
typedef IGenericRemoteSchemaDocumentProvider< SchemaDocument > IRemoteSchemaDocumentProvider
IGenericRemoteSchemaDocumentProvider using SchemaDocument.
typedef GenericSchemaValidator< SchemaDocument, BaseReaderHandler< UTF8< char >, void >, CrtAllocator > SchemaValidator
typedef BasicIStreamWrapper< std::istream > IStreamWrapper
typedef BasicIStreamWrapper< std::wistream > WIStreamWrapper
typedef BasicOStreamWrapper< std::ostream > OStreamWrapper
typedef BasicOStreamWrapper< std::wostream > WOStreamWrapper
typedef unsigned SizeType
Size type (for string lengths, array sizes, etc.)
Enumerations
enum UTFType {
kUTF8 = 0,
kUTF16LE = 1,
kUTF16BE = 2,
kUTF32LE = 3,
kUTF32BE = 4
 }
Runtime-specified UTF encoding type of a stream.
enum ParseErrorCode {
kParseErrorNone = 0,
kParseErrorDocumentEmpty,
kParseErrorDocumentRootNotSingular,
kParseErrorValueInvalid,
kParseErrorObjectMissName,
kParseErrorObjectMissColon,
kParseErrorObjectMissCommaOrCurlyBracket,
kParseErrorArrayMissCommaOrSquareBracket,
kParseErrorStringUnicodeEscapeInvalidHex,
kParseErrorStringUnicodeSurrogateInvalid,
kParseErrorStringEscapeInvalid,
kParseErrorStringMissQuotationMark,
kParseErrorStringInvalidEncoding,
kParseErrorNumberTooBig,
kParseErrorNumberMissFraction,
kParseErrorNumberMissExponent,
kParseErrorTermination,
kParseErrorUnspecificSyntaxError
 }
Error code of parsing.
enum PointerParseErrorCode {
kPointerParseErrorNone = 0,
kPointerParseErrorTokenMustBeginWithSolidus,
kPointerParseErrorInvalidEscape,
kPointerParseErrorInvalidPercentEncoding,
kPointerParseErrorCharacterMustPercentEncode
 }
Error code of parsing.
enum PrettyFormatOptions { kFormatDefault = 0,
kFormatSingleLineArray = 1
 }
Combination of PrettyWriter format flags.
enum Type {
kNullType = 0,
kFalseType = 1,
kTrueType = 2,
kObjectType = 3,
kArrayType = 4,
kStringType = 5,
kNumberType = 6
 }
Type of JSON value.
enum ParseFlag {
kParseNoFlags = 0,
kParseInsituFlag = 1,
kParseValidateEncodingFlag = 2,
kParseIterativeFlag = 4,
kParseStopWhenDoneFlag = 8,
kParseFullPrecisionFlag = 16,
kParseCommentsFlag = 32,
kParseNumbersAsStringsFlag = 64,
kParseTrailingCommasFlag = 128,
kParseNanAndInfFlag = 256,
kParseDefaultFlags = kParseNoFlags
 }
Combination of parseFlags.
enum WriteFlag { kWriteNoFlags = 0,
kWriteValidateEncodingFlag = 1,
kWriteNanAndInfFlag = 2,
kWriteDefaultFlags = kWriteNoFlags
 }
Combination of writeFlags.
Functions
template<typename CharType >
GenericStringRef< CharType > StringRef (const CharType *str)
Mark a character pointer as constant string.
template<typename CharType >
GenericStringRef< CharType > StringRef (const CharType *str, size_t length)
Mark a character pointer as constant string.
template<typename Stream >
void PutUnsafe (Stream &stream, typename Stream::Ch c)
Write character to a stream, presuming buffer is reserved.
const char * GetParseError_En (ParseErrorCode parseErrorCode)
Maps error code of parsing into error message.
template<>
void PutN (FileWriteStream &stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
template<>
void PutN (MemoryBuffer &memoryBuffer, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
template<typename InputStream >
void SkipWhitespace (InputStream &is)
Skip the JSON white spaces in a stream.
const char * SkipWhitespace (const char *p, const char *end)
template<typename Stream >
void PutReserve (Stream &stream, size_t count)
Reserve n characters for writing to a stream.
template<typename Stream , typename Ch >
void PutN (Stream &stream, Ch c, size_t n)
Put N copies of a character to a stream.
template<typename Encoding , typename Allocator >
void PutReserve (GenericStringBuffer< Encoding, Allocator > &stream, size_t count)
template<typename Encoding , typename Allocator >
void PutUnsafe (GenericStringBuffer< Encoding, Allocator > &stream, typename Encoding::Ch c)
template<>
void PutN (GenericStringBuffer< UTF8<> > &stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
Variables
static const SizeType kPointerInvalidIndex = ~SizeType(0)
Represents an invalid index in GenericPointer::Token.
Helper functions for GenericPointer
const GenericPointer< typename T::ValueType > & pointer
const GenericPointer< typename T::ValueType > T2 defaultValue
const GenericPointer< typename T::ValueType > T2 T::AllocatorType & a
const CharType(& source)[N]
const GenericPointer< typename T::ValueType > T2 value
template<typename T >
T::ValueType & CreateValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N>
T::ValueType & CreateValueByPointer (T &root, const CharType(&source)[N], typename T::AllocatorType &a)
template<typename DocumentType >
DocumentType::ValueType & CreateValueByPointer (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer)
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & CreateValueByPointer (DocumentType &document, const CharType(&source)[N])
template<typename T >
T::ValueType * GetValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer, size_t *unresolvedTokenIndex=0)
template<typename T >
const T::ValueType * GetValueByPointer (const T &root, const GenericPointer< typename T::ValueType > &pointer, size_t *unresolvedTokenIndex=0)
template<typename T , typename CharType , size_t N>
T::ValueType * GetValueByPointer (T &root, const CharType(&source)[N], size_t *unresolvedTokenIndex=0)
template<typename T , typename CharType , size_t N>
const T::ValueType * GetValueByPointer (const T &root, const CharType(&source)[N], size_t *unresolvedTokenIndex=0)
template<typename T >
T::ValueType & GetValueByPointerWithDefault (T &root, const GenericPointer< typename T::ValueType > &pointer, const typename T::ValueType &defaultValue, typename T::AllocatorType &a)
template<typename T >
T::ValueType & GetValueByPointerWithDefault (T &root, const GenericPointer< typename T::ValueType > &pointer, const typename T::Ch *defaultValue, typename T::AllocatorType &a)
template<typename T , typename T2 >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >),(typename T::ValueType &)) GetValueByPointerWithDefault(T &root
template<typename T , typename CharType , size_t N>
T::ValueType & GetValueByPointerWithDefault (T &root, const CharType(&source)[N], const typename T::ValueType &defaultValue, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N>
T::ValueType & GetValueByPointerWithDefault (T &root, const CharType(&source)[N], const typename T::Ch *defaultValue, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N, typename T2 >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >),(typename T::ValueType &)) GetValueByPointerWithDefault(T &root
template<typename DocumentType >
DocumentType::ValueType & GetValueByPointerWithDefault (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer, const typename DocumentType::ValueType &defaultValue)
template<typename DocumentType >
DocumentType::ValueType & GetValueByPointerWithDefault (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer, const typename DocumentType::Ch *defaultValue)
template<typename DocumentType , typename T2 >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >),(typename DocumentType::ValueType &)) GetValueByPointerWithDefault(DocumentType &document
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & GetValueByPointerWithDefault (DocumentType &document, const CharType(&source)[N], const typename DocumentType::ValueType &defaultValue)
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & GetValueByPointerWithDefault (DocumentType &document, const CharType(&source)[N], const typename DocumentType::Ch *defaultValue)
template<typename DocumentType , typename CharType , size_t N, typename T2 >
RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >),(typename DocumentType::ValueType &)) GetValueByPointerWithDefault(DocumentType &document
template<typename T >
T::ValueType & SetValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer, typename T::ValueType &value, typename T::AllocatorType &a)
template<typename T >
T::ValueType & SetValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer, const typename T::ValueType &value, typename T::AllocatorType &a)
template<typename T >
T::ValueType & SetValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer, const typename T::Ch *value, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N>
T::ValueType & SetValueByPointer (T &root, const CharType(&source)[N], typename T::ValueType &value, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N>
T::ValueType & SetValueByPointer (T &root, const CharType(&source)[N], const typename T::ValueType &value, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N>
T::ValueType & SetValueByPointer (T &root, const CharType(&source)[N], const typename T::Ch *value, typename T::AllocatorType &a)
template<typename DocumentType >
DocumentType::ValueType & SetValueByPointer (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer, typename DocumentType::ValueType &value)
template<typename DocumentType >
DocumentType::ValueType & SetValueByPointer (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer, const typename DocumentType::ValueType &value)
template<typename DocumentType >
DocumentType::ValueType & SetValueByPointer (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer, const typename DocumentType::Ch *value)
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & SetValueByPointer (DocumentType &document, const CharType(&source)[N], typename DocumentType::ValueType &value)
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & SetValueByPointer (DocumentType &document, const CharType(&source)[N], const typename DocumentType::ValueType &value)
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & SetValueByPointer (DocumentType &document, const CharType(&source)[N], const typename DocumentType::Ch *value)
template<typename T >
T::ValueType & SwapValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer, typename T::ValueType &value, typename T::AllocatorType &a)
template<typename T , typename CharType , size_t N>
T::ValueType & SwapValueByPointer (T &root, const CharType(&source)[N], typename T::ValueType &value, typename T::AllocatorType &a)
template<typename DocumentType >
DocumentType::ValueType & SwapValueByPointer (DocumentType &document, const GenericPointer< typename DocumentType::ValueType > &pointer, typename DocumentType::ValueType &value)
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType & SwapValueByPointer (DocumentType &document, const CharType(&source)[N], typename DocumentType::ValueType &value)
template<typename T >
bool EraseValueByPointer (T &root, const GenericPointer< typename T::ValueType > &pointer)
template<typename T , typename CharType , size_t N>
bool EraseValueByPointer (T &root, const CharType(&source)[N])
Detailed Description
main RapidJSON namespace
See also
RAPIDJSON_NAMESPACE
Typedef Documentation
Document
typedef GenericDocument< UTF8< char >, MemoryPoolAllocator< CrtAllocator >, CrtAllocator > rapidjson::Document
GenericDocument with UTF8 encoding.
Definition at line 2506 of file document.h.
InsituStringStream
typedef GenericInsituStringStream< UTF8<> > rapidjson::InsituStringStream
Insitu string stream with UTF8 encoding.
Definition at line 52 of file fwd.h.
IRemoteSchemaDocumentProvider
typedef IGenericRemoteSchemaDocumentProvider< SchemaDocument > rapidjson::IRemoteSchemaDocumentProvider
IGenericRemoteSchemaDocumentProvider using SchemaDocument.
Definition at line 139 of file fwd.h.
IStreamWrapper
typedef BasicIStreamWrapper<std::istream> rapidjson::IStreamWrapper
Definition at line 119 of file istreamwrapper.h.
MemoryBuffer
typedef GenericMemoryBuffer rapidjson::MemoryBuffer
Definition at line 74 of file fwd.h.
OStreamWrapper
typedef BasicOStreamWrapper<std::ostream> rapidjson::OStreamWrapper
Definition at line 72 of file ostreamwrapper.h.
Pointer
typedef GenericPointer< Value > rapidjson::Pointer
GenericPointer for Value (UTF-8, default allocator).
Definition at line 126 of file fwd.h.
Reader
typedef GenericReader< UTF8<>, UTF8<> > rapidjson::Reader
Reader with UTF8 encoding and default allocator.
Definition at line 88 of file fwd.h.
SchemaDocument
typedef GenericSchemaDocument< Value > rapidjson::SchemaDocument
GenericSchemaDocument using Value type.
Definition at line 136 of file fwd.h.
SchemaValidator
typedef GenericSchemaValidator< SchemaDocument > rapidjson::SchemaValidator
Definition at line 145 of file fwd.h.
SizeType
typedef unsigned rapidjson::SizeType
Size type (for string lengths, array sizes, etc.)
RapidJSON uses 32-bit array/string indices even on 64-bit platforms, instead of using size_t. Users may override the SizeType by defining RAPIDJSON_NO_SIZETYPEDEFINE.
Definition at line 384 of file rapidjson.h.
StringBuffer
typedef GenericStringBuffer< UTF8<> > rapidjson::StringBuffer
String buffer with UTF8 encoding.
Definition at line 59 of file fwd.h.
StringStream
typedef GenericStringStream< UTF8<> > rapidjson::StringStream
String stream with UTF8 encoding.
Definition at line 47 of file fwd.h.
Value
typedef GenericValue< UTF8< char >, MemoryPoolAllocator< CrtAllocator > > rapidjson::Value
GenericValue with UTF8 encoding.
Definition at line 2110 of file document.h.
WIStreamWrapper
typedef BasicIStreamWrapper<std::wistream> rapidjson::WIStreamWrapper
Definition at line 120 of file istreamwrapper.h.
WOStreamWrapper
typedef BasicOStreamWrapper<std::wostream> rapidjson::WOStreamWrapper
Definition at line 73 of file ostreamwrapper.h.
Enumeration Type Documentation
ParseFlag
enum rapidjson::ParseFlag
Combination of parseFlags.
See also
Reader::Parse, Document::Parse, Document::ParseInsitu, Document::ParseStream
Enumerator
kParseNoFlags No flags are set.
kParseInsituFlag In-situ(destructive) parsing.
kParseValidateEncodingFlag Validate encoding of JSON strings.
kParseIterativeFlag Iterative(constant complexity in terms of function call stack size) parsing.
kParseStopWhenDoneFlag After parsing a complete JSON root from stream, stop further processing the rest of stream. When this flag is used, parser will not generate kParseErrorDocumentRootNotSingular error.
kParseFullPrecisionFlag Parse number in full precision (but slower).
kParseCommentsFlag Allow one-line (//) and multi-line (/**/) comments.
kParseNumbersAsStringsFlag Parse all numbers (ints/doubles) as strings.
kParseTrailingCommasFlag Allow trailing commas at the end of objects and arrays.
kParseNanAndInfFlag Allow parsing NaN, Inf, Infinity, -Inf and -Infinity as doubles.
kParseDefaultFlags Default parse flags. Can be customized by defining RAPIDJSON_PARSE_DEFAULT_FLAGS.
Definition at line 145 of file reader.h.
               {
    kParseNoFlags = 0,
    kParseInsituFlag = 1,
    kParseValidateEncodingFlag = 2,
    kParseIterativeFlag = 4,
    kParseStopWhenDoneFlag = 8,
    kParseFullPrecisionFlag = 16,
    kParseCommentsFlag = 32,
    kParseNumbersAsStringsFlag = 64,
    kParseTrailingCommasFlag = 128,
    kParseNanAndInfFlag = 256,
    kParseDefaultFlags = RAPIDJSON_PARSE_DEFAULT_FLAGS
};
PrettyFormatOptions
enum rapidjson::PrettyFormatOptions
Combination of PrettyWriter format flags.
See also
PrettyWriter::SetFormatOptions
Enumerator
kFormatDefault Default pretty formatting.
kFormatSingleLineArray Format arrays on a single line.
Definition at line 35 of file prettywriter.h.
                         {
    kFormatDefault = 0,
    kFormatSingleLineArray = 1
};
Type
enum rapidjson::Type
Type of JSON value.
Enumerator
kNullType null
kFalseType false
kTrueType true
kObjectType object
kArrayType array
kStringType string
kNumberType number
Definition at line 644 of file rapidjson.h.
          {
    kNullType = 0,
    kFalseType = 1,
    kTrueType = 2,
    kObjectType = 3,
    kArrayType = 4,
    kStringType = 5,
    kNumberType = 6
};
UTFType
enum rapidjson::UTFType
Runtime-specified UTF encoding type of a stream.
Enumerator
kUTF8 UTF-8.
kUTF16LE UTF-16 little endian.
kUTF16BE UTF-16 big endian.
kUTF32LE UTF-32 little endian.
kUTF32BE UTF-32 big endian.
Definition at line 603 of file encodings.h.
             {
    kUTF8 = 0,
    kUTF16LE = 1,
    kUTF16BE = 2,
    kUTF32LE = 3,
    kUTF32BE = 4
};
WriteFlag
enum rapidjson::WriteFlag
Combination of writeFlags.
Enumerator
kWriteNoFlags No flags are set.
kWriteValidateEncodingFlag Validate encoding of JSON strings.
kWriteNanAndInfFlag Allow writing of Infinity, -Infinity and NaN.
kWriteDefaultFlags Default write flags. Can be customized by defining RAPIDJSON_WRITE_DEFAULT_FLAGS.
Definition at line 65 of file writer.h.
               {
    kWriteNoFlags = 0,
    kWriteValidateEncodingFlag = 1,
    kWriteNanAndInfFlag = 2,
    kWriteDefaultFlags = RAPIDJSON_WRITE_DEFAULT_FLAGS
};
Function Documentation
CreateValueByPointer() [1/4]
template<typename T >
T::ValueType& rapidjson::CreateValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer, typename T::AllocatorType & a)
Definition at line 1117 of file pointer.h.
                                                                                                                                   {
    return pointer.Create(root, a);
}
References a, and pointer.
CreateValueByPointer() [2/4]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::CreateValueByPointer (T & root, const CharType(&) source[N], typename T::AllocatorType & a)
Definition at line 1122 of file pointer.h.
                                                                                                           {
    return GenericPointer<typename T::ValueType>(source, N - 1).Create(root, a);
}
References a, and source.
CreateValueByPointer() [3/4]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::CreateValueByPointer (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer)
Definition at line 1129 of file pointer.h.
                                                                                                                                            {
    return pointer.Create(document);
}
References pointer.
CreateValueByPointer() [4/4]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::CreateValueByPointer (DocumentType & document, const CharType(&) source[N])
Definition at line 1134 of file pointer.h.
                                                                                                         {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).Create(document);
}
References source.
EraseValueByPointer() [1/2]
template<typename T >
bool rapidjson::EraseValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer)
Definition at line 1397 of file pointer.h.
                                                                                      {
    return pointer.Erase(root);
}
References pointer.
EraseValueByPointer() [2/2]
template<typename T , typename CharType , size_t N>
bool rapidjson::EraseValueByPointer (T & root, const CharType(&) source[N])
Definition at line 1402 of file pointer.h.
                                                              {
    return GenericPointer<typename T::ValueType>(source, N - 1).Erase(root);
}
References source.
GetValueByPointer() [1/4]
template<typename T >
T::ValueType* rapidjson::GetValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer, size_t * unresolvedTokenIndex = 0)
Definition at line 1141 of file pointer.h.
                                                                                                                                      {
    return pointer.Get(root, unresolvedTokenIndex);
}
References pointer.
GetValueByPointer() [2/4]
template<typename T >
const T::ValueType* rapidjson::GetValueByPointer (const T & root, const GenericPointer< typename T::ValueType > & pointer, size_t * unresolvedTokenIndex = 0)
Definition at line 1146 of file pointer.h.
                                                                                                                                                  {
    return pointer.Get(root, unresolvedTokenIndex);
}
References pointer.
GetValueByPointer() [3/4]
template<typename T , typename CharType , size_t N>
T::ValueType* rapidjson::GetValueByPointer (T & root, const CharType(&) source[N], size_t * unresolvedTokenIndex = 0)
Definition at line 1151 of file pointer.h.
                                                                                                               {
    return GenericPointer<typename T::ValueType>(source, N - 1).Get(root, unresolvedTokenIndex);
}
References source.
GetValueByPointer() [4/4]
template<typename T , typename CharType , size_t N>
const T::ValueType* rapidjson::GetValueByPointer (const T & root, const CharType(&) source[N], size_t * unresolvedTokenIndex = 0)
Definition at line 1156 of file pointer.h.
                                                                                                                          {
    return GenericPointer<typename T::ValueType>(source, N - 1).Get(root, unresolvedTokenIndex);
}
References source.
GetValueByPointerWithDefault() [1/8]
template<typename T >
T::ValueType& rapidjson::GetValueByPointerWithDefault (T & root, const GenericPointer< typename T::ValueType > & pointer, const typename T::ValueType & defaultValue, typename T::AllocatorType & a)
Definition at line 1163 of file pointer.h.
                                                                                                                                                                                    {
    return pointer.GetWithDefault(root, defaultValue, a);
}
References a, defaultValue, and pointer.
GetValueByPointerWithDefault() [2/8]
template<typename T >
T::ValueType& rapidjson::GetValueByPointerWithDefault (T & root, const GenericPointer< typename T::ValueType > & pointer, const typename T::Ch * defaultValue, typename T::AllocatorType & a)
Definition at line 1168 of file pointer.h.
                                                                                                                                                                             {
    return pointer.GetWithDefault(root, defaultValue, a);
}
References a, defaultValue, and pointer.
GetValueByPointerWithDefault() [3/8]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::GetValueByPointerWithDefault (T & root, const CharType(&) source[N], const typename T::ValueType & defaultValue, typename T::AllocatorType & a)
Definition at line 1186 of file pointer.h.
                                                                                                                                                            {
    return GenericPointer<typename T::ValueType>(source, N - 1).GetWithDefault(root, defaultValue, a);
}
References a, defaultValue, and source.
GetValueByPointerWithDefault() [4/8]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::GetValueByPointerWithDefault (T & root, const CharType(&) source[N], const typename T::Ch * defaultValue, typename T::AllocatorType & a)
Definition at line 1191 of file pointer.h.
                                                                                                                                                     {
    return GenericPointer<typename T::ValueType>(source, N - 1).GetWithDefault(root, defaultValue, a);
}
References a, defaultValue, and source.
GetValueByPointerWithDefault() [5/8]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::GetValueByPointerWithDefault (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer, const typename DocumentType::ValueType & defaultValue)
Definition at line 1211 of file pointer.h.
                                                                                                                                                                                                        {
    return pointer.GetWithDefault(document, defaultValue);
}
References defaultValue, and pointer.
GetValueByPointerWithDefault() [6/8]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::GetValueByPointerWithDefault (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer, const typename DocumentType::Ch * defaultValue)
Definition at line 1216 of file pointer.h.
                                                                                                                                                                                                 {
    return pointer.GetWithDefault(document, defaultValue);
}
References defaultValue, and pointer.
GetValueByPointerWithDefault() [7/8]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::GetValueByPointerWithDefault (DocumentType & document, const CharType(&) source[N], const typename DocumentType::ValueType & defaultValue)
Definition at line 1234 of file pointer.h.
                                                                                                                                                                     {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).GetWithDefault(document, defaultValue);
}
References defaultValue, and source.
GetValueByPointerWithDefault() [8/8]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::GetValueByPointerWithDefault (DocumentType & document, const CharType(&) source[N], const typename DocumentType::Ch * defaultValue)
Definition at line 1239 of file pointer.h.
                                                                                                                                                              {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).GetWithDefault(document, defaultValue);
}
References defaultValue, and source.
PutN() [1/4]
template<>
void rapidjson::PutN (MemoryBuffer & memoryBuffer, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
Definition at line 64 of file memorybuffer.h.
                                                               {
    std::memset(memoryBuffer.stack_.Push<char>(n), c, n * sizeof(c));
}
References rapidjson::GenericMemoryBuffer< Allocator >::stack_.
PutN() [2/4]
template<>
void rapidjson::PutN (FileWriteStream & stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
Definition at line 94 of file filewritestream.h.
                                                            {
    stream.PutN(c, n);
}
References rapidjson::FileWriteStream::PutN().
Referenced by rapidjson::PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
PutN() [3/4]
template<typename Stream , typename Ch >
void rapidjson::PutN (Stream & stream, Ch c, size_t n)
Put N copies of a character to a stream.
Definition at line 97 of file stream.h.
                                                 {
    PutReserve(stream, n);
    for (size_t i = 0; i < n; i++)
        PutUnsafe(stream, c);
}
References PutReserve(), and PutUnsafe().
PutN() [4/4]
template<>
void rapidjson::PutN (GenericStringBuffer< UTF8<> > & stream, char c, size_t n)
Implement specialized version of PutN() with memset() for better performance.
Definition at line 111 of file stringbuffer.h.
                                                                         {
    std::memset(stream.stack_.Push<char>(n), c, n * sizeof(c));
}
PutReserve() [1/2]
template<typename Stream >
void rapidjson::PutReserve (Stream & stream, size_t count)
Reserve n characters for writing to a stream.
Definition at line 84 of file stream.h.
                                                     {
    (void)stream;
    (void)count;
}
Referenced by PutN(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
PutReserve() [2/2]
template<typename Encoding , typename Allocator >
void rapidjson::PutReserve (GenericStringBuffer< Encoding, Allocator > & stream, size_t count)
Definition at line 100 of file stringbuffer.h.
                                                                                       {
    stream.Reserve(count);
}
PutUnsafe() [1/2]
template<typename Encoding , typename Allocator >
void rapidjson::PutUnsafe (GenericStringBuffer< Encoding, Allocator > & stream, typename Encoding::Ch c)
Definition at line 105 of file stringbuffer.h.
                                                                                               {
    stream.PutUnsafe(c);
}
PutUnsafe() [2/2]
template<typename Stream >
void rapidjson::PutUnsafe (Stream & stream, typename Stream::Ch c)
Write character to a stream, presuming buffer is reserved.
Definition at line 91 of file stream.h.
                                                           {
    stream.Put(c);
}
Referenced by rapidjson::UTF8< CharType >::EncodeUnsafe(), rapidjson::UTF16< CharType >::EncodeUnsafe(), rapidjson::UTF32< CharType >::EncodeUnsafe(), rapidjson::ASCII< CharType >::EncodeUnsafe(), PutN(), rapidjson::Transcoder< Encoding, Encoding >::TranscodeUnsafe(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString(), rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
RAPIDJSON_DISABLEIF_RETURN() [1/4]
template<typename T , typename T2 >
rapidjson::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >) , (typename T::ValueType &)) &
RAPIDJSON_DISABLEIF_RETURN() [2/4]
template<typename T , typename CharType , size_t N, typename T2 >
rapidjson::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >) , (typename T::ValueType &)) &
RAPIDJSON_DISABLEIF_RETURN() [3/4]
template<typename DocumentType , typename T2 >
rapidjson::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >) , (typename DocumentType::ValueType &)) &
RAPIDJSON_DISABLEIF_RETURN() [4/4]
template<typename DocumentType , typename CharType , size_t N, typename T2 >
rapidjson::RAPIDJSON_DISABLEIF_RETURN ((internal::OrExpr< internal::IsPointer< T2 >, internal::IsGenericValue< T2 > >) , (typename DocumentType::ValueType &)) &
SetValueByPointer() [1/12]
template<typename T >
T::ValueType& rapidjson::SetValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer, typename T::ValueType & value, typename T::AllocatorType & a)
Definition at line 1259 of file pointer.h.
                                                                                                                                                            {
    return pointer.Set(root, value, a);
}
References a, pointer, and value.
SetValueByPointer() [2/12]
template<typename T >
T::ValueType& rapidjson::SetValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer, const typename T::ValueType & value, typename T::AllocatorType & a)
Definition at line 1264 of file pointer.h.
                                                                                                                                                                  {
    return pointer.Set(root, value, a);
}
References a, pointer, and value.
SetValueByPointer() [3/12]
template<typename T >
T::ValueType& rapidjson::SetValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer, const typename T::Ch * value, typename T::AllocatorType & a)
Definition at line 1269 of file pointer.h.
                                                                                                                                                           {
    return pointer.Set(root, value, a);
}
References a, pointer, and value.
SetValueByPointer() [4/12]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::SetValueByPointer (T & root, const CharType(&) source[N], typename T::ValueType & value, typename T::AllocatorType & a)
Definition at line 1287 of file pointer.h.
                                                                                                                                    {
    return GenericPointer<typename T::ValueType>(source, N - 1).Set(root, value, a);
}
References a, source, and value.
SetValueByPointer() [5/12]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::SetValueByPointer (T & root, const CharType(&) source[N], const typename T::ValueType & value, typename T::AllocatorType & a)
Definition at line 1292 of file pointer.h.
                                                                                                                                          {
    return GenericPointer<typename T::ValueType>(source, N - 1).Set(root, value, a);
}
References a, source, and value.
SetValueByPointer() [6/12]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::SetValueByPointer (T & root, const CharType(&) source[N], const typename T::Ch * value, typename T::AllocatorType & a)
Definition at line 1297 of file pointer.h.
                                                                                                                                   {
    return GenericPointer<typename T::ValueType>(source, N - 1).Set(root, value, a);
}
References a, source, and value.
SetValueByPointer() [7/12]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::SetValueByPointer (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer, typename DocumentType::ValueType & value)
Definition at line 1317 of file pointer.h.
                                                                                                                                                                                {
    return pointer.Set(document, value);
}
References pointer, and value.
SetValueByPointer() [8/12]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::SetValueByPointer (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer, const typename DocumentType::ValueType & value)
Definition at line 1322 of file pointer.h.
                                                                                                                                                                                      {
    return pointer.Set(document, value);
}
References pointer, and value.
SetValueByPointer() [9/12]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::SetValueByPointer (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer, const typename DocumentType::Ch * value)
Definition at line 1327 of file pointer.h.
                                                                                                                                                                               {
    return pointer.Set(document, value);
}
References pointer, and value.
SetValueByPointer() [10/12]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::SetValueByPointer (DocumentType & document, const CharType(&) source[N], typename DocumentType::ValueType & value)
Definition at line 1345 of file pointer.h.
                                                                                                                                             {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).Set(document, value);
}
References source, and value.
SetValueByPointer() [11/12]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::SetValueByPointer (DocumentType & document, const CharType(&) source[N], const typename DocumentType::ValueType & value)
Definition at line 1350 of file pointer.h.
                                                                                                                                                   {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).Set(document, value);
}
References source, and value.
SetValueByPointer() [12/12]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::SetValueByPointer (DocumentType & document, const CharType(&) source[N], const typename DocumentType::Ch * value)
Definition at line 1355 of file pointer.h.
                                                                                                                                            {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).Set(document, value);
}
References source, and value.
SkipWhitespace() [1/2]
template<typename InputStream >
void rapidjson::SkipWhitespace (InputStream & is)
Skip the JSON white spaces in a stream.
Parameters
is A input stream for skipping white spaces.
Note
This function has SSE2/SSE4.2 specialization.
Definition at line 264 of file reader.h.
                                     {
    internal::StreamLocalCopy<InputStream> copy(is);
    InputStream& s(copy.s);
    typename InputStream::Ch c;
    while ((c = s.Peek()) == ' ' || c == '\n' || c == '\r' || c == '\t')
        s.Take();
}
SkipWhitespace() [2/2]
const char* rapidjson::SkipWhitespace (const char * p, const char * end)
Definition at line 273 of file reader.h.
                                                                  {
    while (p != end && (*p == ' ' || *p == '\n' || *p == '\r' || *p == '\t'))
        ++p;
    return p;
}
Referenced by rapidjson::GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SkipWhitespaceAndComments().
StringRef() [1/2]
template<typename CharType >
GenericStringRef< CharType > StringRef (const CharType * str)
Mark a character pointer as constant string.
Mark a plain character pointer as a `string literal`. This function can be used to avoid copying a character string to be referenced as a value in a JSON GenericValue object, if the string's lifetime is known to be valid long enough.
Template Parameters
CharType Character type of the string
Parameters
str Constant string, lifetime assumed to be longer than the use of the string in e.g. a GenericValue
Returns
GenericStringRef string reference object
See also
GenericValue::GenericValue(StringRefType), GenericValue::operator=(StringRefType), GenericValue::SetString(StringRefType), GenericValue::PushBack(StringRefType, Allocator&), GenericValue::AddMember
Definition at line 364 of file document.h.
                                                                 {
    return GenericStringRef<CharType>(str);
}
StringRef() [2/2]
template<typename CharType >
GenericStringRef< CharType > StringRef (const CharType * str, size_t length)
Mark a character pointer as constant string.
Mark a plain character pointer as a `string literal`. This function can be used to avoid copying a character string to be referenced as a value in a JSON GenericValue object, if the string's lifetime is known to be valid long enough.
This version has better performance with supplied length, and also supports string containing null characters.
Template Parameters
CharType character type of the string
Parameters
str Constant string, lifetime assumed to be longer than the use of the string in e.g. a GenericValue
length The length of source string.
Returns
GenericStringRef string reference object
Definition at line 384 of file document.h.
                                                                                {
    return GenericStringRef<CharType>(str, SizeType(length));
}
Referenced by rapidjson::GenericValue< EncodingType, Allocator >::GenericValue().
SwapValueByPointer() [1/4]
template<typename T >
T::ValueType& rapidjson::SwapValueByPointer (T & root, const GenericPointer< typename T::ValueType > & pointer, typename T::ValueType & value, typename T::AllocatorType & a)
Definition at line 1375 of file pointer.h.
                                                                                                                                                             {
    return pointer.Swap(root, value, a);
}
References a, pointer, and value.
SwapValueByPointer() [2/4]
template<typename T , typename CharType , size_t N>
T::ValueType& rapidjson::SwapValueByPointer (T & root, const CharType(&) source[N], typename T::ValueType & value, typename T::AllocatorType & a)
Definition at line 1380 of file pointer.h.
                                                                                                                                     {
    return GenericPointer<typename T::ValueType>(source, N - 1).Swap(root, value, a);
}
References a, source, rapidjson::GenericPointer< ValueType, Allocator >::Swap(), and value.
SwapValueByPointer() [3/4]
template<typename DocumentType >
DocumentType::ValueType& rapidjson::SwapValueByPointer (DocumentType & document, const GenericPointer< typename DocumentType::ValueType > & pointer, typename DocumentType::ValueType & value)
Definition at line 1385 of file pointer.h.
                                                                                                                                                                                 {
    return pointer.Swap(document, value);
}
References pointer, and value.
SwapValueByPointer() [4/4]
template<typename DocumentType , typename CharType , size_t N>
DocumentType::ValueType& rapidjson::SwapValueByPointer (DocumentType & document, const CharType(&) source[N], typename DocumentType::ValueType & value)
Definition at line 1390 of file pointer.h.
                                                                                                                                              {
    return GenericPointer<typename DocumentType::ValueType>(source, N - 1).Swap(document, value);
}
References source, rapidjson::GenericPointer< ValueType, Allocator >::Swap(), and value.
Variable Documentation
a
const GenericPointer< typename T::ValueType > T2 T::AllocatorType & rapidjson::a
Initial value:
{
    return pointer.GetWithDefault(root, defaultValue, a)
Definition at line 1181 of file pointer.h.
Referenced by rapidjson::internal::Schema< SchemaDocumentType >::AddUniqueElement(), rapidjson::internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf(), CreateValueByPointer(), rapidjson::internal::BigInteger::Difference(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), rapidjson::GenericValue< EncodingType, Allocator >::GenericValue(), GetValueByPointerWithDefault(), rapidjson::internal::GenericRegex< Encoding, Allocator >::Min(), rapidjson::internal::Min3(), rapidjson::internal::BigInteger::MulAdd64(), rapidjson::internal::DiyFp::operator *(), rapidjson::GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema(), rapidjson::internal::TypeHelper< ValueType, const typename ValueType::Ch * >::Set(), SetValueByPointer(), rapidjson::internal::StrtodBigInteger(), rapidjson::internal::Swap(), SwapValueByPointer(), rapidjson::internal::u32toa(), and rapidjson::internal::u64toa().
defaultValue
const GenericPointer< typename DocumentType::ValueType > T2 rapidjson::defaultValue
Initial value:
{
    return pointer.GetWithDefault(document, defaultValue)
Definition at line 1181 of file pointer.h.
Referenced by GetValueByPointerWithDefault().
kPointerInvalidIndex
const SizeType rapidjson::kPointerInvalidIndex = ~SizeType(0) [static]
Represents an invalid index in GenericPointer::Token.
Definition at line 31 of file pointer.h.
Referenced by rapidjson::GenericPointer< ValueType, Allocator >::Append().
pointer
const GenericPointer< typename DocumentType::ValueType > & rapidjson::pointer
Definition at line 1181 of file pointer.h.
Referenced by rapidjson::GenericSchemaDocument< ValueT, Allocator >::CreateSchema(), rapidjson::GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive(), CreateValueByPointer(), EraseValueByPointer(), rapidjson::GenericSchemaDocument< ValueT, Allocator >::GetSchema(), GetValueByPointer(), GetValueByPointerWithDefault(), rapidjson::GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema(), SetValueByPointer(), and SwapValueByPointer().
source
const CharType(& rapidjson::source
Definition at line 1204 of file pointer.h.
Referenced by CreateValueByPointer(), rapidjson::internal::Schema< SchemaDocumentType >::EndObject(), EraseValueByPointer(), rapidjson::GenericPointer< ValueType, Allocator >::GenericPointer(), rapidjson::internal::GenericRegex< Encoding, Allocator >::GenericRegex(), GetValueByPointer(), GetValueByPointerWithDefault(), rapidjson::GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema(), SetValueByPointer(), and SwapValueByPointer().
value
const GenericPointer< typename DocumentType::ValueType > T2 rapidjson::value
Initial value:
{
    return pointer.Set(document, value)
Definition at line 1282 of file pointer.h.
Referenced by rapidjson::GenericObject< Const, ValueT >::AddMember(), rapidjson::internal::Schema< SchemaDocumentType >::AssignIfExist(), rapidjson::internal::Schema< SchemaDocumentType >::CreatePattern(), rapidjson::internal::dtoa(), rapidjson::GenericValue< EncodingType, Allocator >::GenericValue(), rapidjson::internal::Schema< SchemaDocumentType >::GetMember(), rapidjson::internal::Grisu2(), rapidjson::internal::i32toa(), rapidjson::internal::i64toa(), rapidjson::GenericArray< Const, ValueT >::PushBack(), rapidjson::internal::Schema< SchemaDocumentType >::Schema(), SetValueByPointer(), SwapValueByPointer(), rapidjson::internal::u32toa(), and rapidjson::internal::u64toa().