rapidjson::GenericStringStream< Encoding > Struct Template Reference
Read-only string stream.
#include <fwd.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
GenericStringStream (const Ch *src)
Ch Peek () const
Ch Take ()
size_t Tell () const
Ch * PutBegin ()
void Put (Ch)
void Flush ()
size_t PutEnd (Ch *)
Data Fields
const Ch * src_
Current read position.
const Ch * head_
Original head of the string.
Detailed Description
template<typename Encoding>
struct rapidjson::GenericStringStream< Encoding >
Read-only string stream.
Note
implements Stream concept
Definition at line 47 of file fwd.h.
Member Typedef Documentation
Ch
template<typename Encoding>
typedef Encoding::Ch rapidjson::GenericStringStream< Encoding >::Ch
Definition at line 155 of file stream.h.
Constructor & Destructor Documentation
GenericStringStream()
template<typename Encoding>
rapidjson::GenericStringStream< Encoding >::GenericStringStream (const Ch * src)
Definition at line 157 of file stream.h.
: src_(src), head_(src) {}
Member Function Documentation
Flush()
template<typename Encoding>
void rapidjson::GenericStringStream< Encoding >::Flush ()
Definition at line 165 of file stream.h.
{ RAPIDJSON_ASSERT(false); }
References RAPIDJSON_ASSERT.
Peek()
template<typename Encoding>
Ch rapidjson::GenericStringStream< Encoding >::Peek () const
Definition at line 159 of file stream.h.
{ return *src_; }
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
Put()
template<typename Encoding>
void rapidjson::GenericStringStream< Encoding >::Put (Ch)
Definition at line 164 of file stream.h.
{ RAPIDJSON_ASSERT(false); }
References RAPIDJSON_ASSERT.
PutBegin()
template<typename Encoding>
Ch* rapidjson::GenericStringStream< Encoding >::PutBegin ()
Definition at line 163 of file stream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutEnd()
template<typename Encoding>
size_t rapidjson::GenericStringStream< Encoding >::PutEnd (Ch *)
Definition at line 166 of file stream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
Take()
template<typename Encoding>
Ch rapidjson::GenericStringStream< Encoding >::Take ()
Definition at line 160 of file stream.h.
{ return *src_++; }
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
Tell()
template<typename Encoding>
size_t rapidjson::GenericStringStream< Encoding >::Tell () const
Definition at line 161 of file stream.h.
{ return static_cast<size_t>(src_ - head_); }
Referenced by rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::ScanWriteUnescapedString(), and rapidjson::Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue().
Field Documentation
head_
template<typename Encoding>
const Ch* rapidjson::GenericStringStream< Encoding >::head_
Original head of the string.
Definition at line 169 of file stream.h.
src_
template<typename Encoding>
const Ch* rapidjson::GenericStringStream< Encoding >::src_
Current read position.
Definition at line 168 of file stream.h.
Referenced by rapidjson::internal::CountStringCodePoint().
The documentation for this struct was generated from the following files:
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/fwd.h
D:/cloned repo trainawear/train-A-wear/Server/rapidjson/stream.h