com.example.trainawearapplication.ClassicSquat Class Reference
Public Member Functions
void enterSquatInstr (View view)
void setViewText (TextView view, String text)
Static Public Member Functions
static int getInstruction ()
static void setInstruction (int instruction)
Implements the instruction obtained from the switch cases.
static String showFeedback (String instructionDef)
Switch case that decides on the feedback to be printed.
Static Public Attributes
static int instruction = 1
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Private Member Functions
void clientEnd ()
Private Attributes
int squatImages []
Create Carousel view with three images.
String [] squatImagesTitle
final int PORT = 31415
Thread udpListener
ClientSend udpSender
Detailed Description
Definition at line 18 of file ClassicSquat.java.
Member Function Documentation
clientEnd()
void com.example.trainawearapplication.ClassicSquat.clientEnd () [private]
Definition at line 163 of file ClassicSquat.java.
                            {
// udpClientThread = null;
        textViewState.setText("clientEnd()");
        buttonConnect.setEnabled(true);
    }
enterSquatInstr()
void com.example.trainawearapplication.ClassicSquat.enterSquatInstr (View view)
Definition at line 111 of file ClassicSquat.java.
                                           {
        Intent squat_instr = new Intent(this, SquatInstr.class);
        startActivity(squat_instr);
    }
getInstruction()
static int com.example.trainawearapplication.ClassicSquat.getInstruction () [static]
Definition at line 39 of file ClassicSquat.java.
                                       {
        return instruction;
    }
References com.example.trainawearapplication.ClassicSquat.instruction.
onCreate()
void com.example.trainawearapplication.ClassicSquat.onCreate (Bundle savedInstanceState) [protected]
Definition at line 63 of file ClassicSquat.java.
                                                       {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_classic_squat);
        // create activity from parent
        Intent classicSquat = getIntent();
        // set carousel view
        CarouselView carouselView = findViewById(R.id.carousel);
        carouselView.setPageCount(squatImages.length);
        carouselView.setImageListener(new ImageListener() {
            @Override
            public void setImageForPosition(int position, ImageView imageView) {
                imageView.setImageResource(squatImages[position]);
            }
        });
        carouselView.setImageClickListener(new ImageClickListener() {
            @Override
            public void onClick(int position) {
                Toast.makeText(ClassicSquat.this, squatImagesTitle[position], Toast.LENGTH_SHORT).show();
            }
        });
        // buttons and text fields for UDPclient thread and feedback
        buttonConnect = findViewById(R.id.buttonStartSquatClassic); // in History
        buttonDisconnect = findViewById(R.id.buttonStopSquatClassic); // in History
        textViewState = findViewById(R.id.state); // store IP address after handshake
        textViewRx = findViewById(R.id.received); // store numbers for feedback
        textFeedback = findViewById(R.id.feedback); // in Squat
        messageView = findViewById(R.id.message);
        buttonConnect.setOnClickListener(buttonConnectOnClickListener);
        buttonDisconnect.setOnClickListener(buttonDisonnectOnClickListener);
        udpClientHandler = new com.example.trainawearapplication.UdpClientHandler();
        Log.d(TAG, "Start listening for messages");
        udpListener = new Thread(new com.example.trainawearapplication.ClientListen(PORT, textViewState, udpClientHandler));
        udpListener.start();
        udpSender = new ClientSend("255.255.255.255", PORT);
        Log.d(TAG, "sending to " + textViewState.getText().toString());
        udpSender.execute("train-a-wear ready");
    }
References com.example.trainawearapplication.R.layout.activity_classic_squat, com.example.trainawearapplication.R.id.buttonStartSquatClassic, com.example.trainawearapplication.R.id.buttonStopSquatClassic, com.example.trainawearapplication.R.id.carousel, com.example.trainawearapplication.R.id.feedback, com.example.trainawearapplication.R.id.message, com.example.trainawearapplication.ClassicSquat.PORT, com.example.trainawearapplication.R.id.received, com.example.trainawearapplication.ClassicSquat.squatImages, com.example.trainawearapplication.ClassicSquat.squatImagesTitle, com.example.trainawearapplication.R.id.state, com.example.trainawearapplication.ClassicSquat.udpListener, and com.example.trainawearapplication.ClassicSquat.udpSender.
setInstruction()
static void com.example.trainawearapplication.ClassicSquat.setInstruction (int instruction) [static]
Implements the instruction obtained from the switch cases.
Parameters
instruction - variable used to decide on the message to be displayed
Definition at line 47 of file ClassicSquat.java.
                                                       {
        ClassicSquat.instruction = instruction;
    }
References com.example.trainawearapplication.ClassicSquat.instruction.
setViewText()
void com.example.trainawearapplication.ClassicSquat.setViewText (TextView view, String text)
Implements com.example.trainawearapplication.UpdateFeedback.
Definition at line 208 of file ClassicSquat.java.
                                                        {
        view.setText(text);
    }
showFeedback()
static String com.example.trainawearapplication.ClassicSquat.showFeedback (String instructionDef) [static]
Switch case that decides on the feedback to be printed.
Parameters
instructionDef The message from RPI that encodes a defect/situation found by the algorithm on the RPI
Returns
The feedback that will be printed using the thread handler, UdpClientHandler
Definition at line 176 of file ClassicSquat.java.
                                                             {
        switch (instructionDef){
            case "0":
                return("Ready to start");
            case "1":
                return ("Let's go!");
            case "2":
                return("Knees caving in: Keep your knees in line with your toes");
            case "3":
                return("Your back is bending, keep it straight while tensing your abs");
            case "4":
                return ("Bring the weight down slowly and increase speed when lifting");
            case "5":
                return ("Try to keep you back in a neutral position, don't lift your hips");
            case "6":
                return ("If you keep your hips steady, the abs are working harder");
            case "7":
                return ("For an effective push up, bring your chest close to the ground");
            default:
                return("You're doing great, keep going!");
        }
    }
Referenced by com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase0(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase1(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase2(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase3(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase6(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCaseDefault(), and com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCaseFail().
Member Data Documentation
instruction
int com.example.trainawearapplication.ClassicSquat.instruction = 1 [static]
Definition at line 25 of file ClassicSquat.java.
Referenced by com.example.trainawearapplication.ClassicSquat.getInstruction(), com.example.trainawearapplication.Plank.setInstruction(), and com.example.trainawearapplication.ClassicSquat.setInstruction().
PORT
final int com.example.trainawearapplication.ClassicSquat.PORT = 31415 [private]
Definition at line 57 of file ClassicSquat.java.
Referenced by com.example.trainawearapplication.ClassicSquat.onCreate().
squatImages
int com.example.trainawearapplication.ClassicSquat.squatImages[] [private]
Initial value:
= new int[]{
            R.drawable.squatstart1, R.drawable.squatmed3, R.drawable.squatend1
    }
Create Carousel view with three images.
Definition at line 29 of file ClassicSquat.java.
Referenced by com.example.trainawearapplication.ClassicSquat.onCreate().
squatImagesTitle
String [] com.example.trainawearapplication.ClassicSquat.squatImagesTitle [private]
Initial value:
= new String[]{
            "Squat1", "Squat2", "Squat3"
    }
Definition at line 33 of file ClassicSquat.java.
Referenced by com.example.trainawearapplication.ClassicSquat.onCreate().
udpListener
Thread com.example.trainawearapplication.ClassicSquat.udpListener [private]
Definition at line 58 of file ClassicSquat.java.
Referenced by com.example.trainawearapplication.ClassicSquat.onCreate().
udpSender
ClientSend com.example.trainawearapplication.ClassicSquat.udpSender [private]
Definition at line 59 of file ClassicSquat.java.
Referenced by com.example.trainawearapplication.ClassicSquat.onCreate().
The documentation for this class was generated from the following file:
src/main/java/com/example/trainawearapplication/ClassicSquat.java