com.example.trainawearapplication.UdpClientHandler Class Reference
Public Member Functions
UdpClientHandler ()
void handleMessage (Message msg)
Static Public Attributes
static final int UPDATE_STATE = 0
static final int UPDATE_MSG = 1
static final int UPDATE_PLANK = 2
static final int UPDATE_END = 3
Private Member Functions
void updateRxMsg (String rxmsg)
Method that updates the receive field with the received String; used to read the String.
void updateState (String state)
Method that displays the IP address in invisible field.
Private Attributes
MainActivity parent
Detailed Description
Definition at line 20 of file UdpClientHandler.java.
Constructor & Destructor Documentation
UdpClientHandler()
com.example.trainawearapplication.UdpClientHandler.UdpClientHandler ()
Definition at line 35 of file UdpClientHandler.java.
                              {
        super();
        this.parent = parent;
    }
References com.example.trainawearapplication.UdpClientHandler.parent.
Referenced by com.example.trainawearapplication.UdpClientHandler.handleMessage().
Member Function Documentation
handleMessage()
void com.example.trainawearapplication.UdpClientHandler.handleMessage (Message msg)
Definition at line 42 of file UdpClientHandler.java.
                                           {
        udpClientHandler = new UdpClientHandler();
        switch (msg.what){
            case UPDATE_STATE:
                udpClientHandler.updateState((String)msg.obj);
                break;
            case UPDATE_MSG:
                udpClientHandler.updateRxMsg((String)msg.obj);
                textFeedback.setText(showFeedback((String)msg.obj));
                break;
            default:
                super.handleMessage(msg);
        }
    }
References com.example.trainawearapplication.UdpClientHandler.UdpClientHandler(), com.example.trainawearapplication.UdpClientHandler.UPDATE_MSG, com.example.trainawearapplication.UdpClientHandler.UPDATE_STATE, com.example.trainawearapplication.UdpClientHandler.updateRxMsg(), and com.example.trainawearapplication.UdpClientHandler.updateState().
updateRxMsg()
void com.example.trainawearapplication.UdpClientHandler.updateRxMsg (String rxmsg) [private]
Method that updates the receive field with the received String; used to read the String.
Parameters
rxmsg
Definition at line 61 of file UdpClientHandler.java.
                                           {
        textViewRx.setText(rxmsg + "\n");
        Log.d(TAG, "on text update");
    }
Referenced by com.example.trainawearapplication.UdpClientHandler.handleMessage().
updateState()
void com.example.trainawearapplication.UdpClientHandler.updateState (String state) [private]
Method that displays the IP address in invisible field.
Parameters
state Variable displays the IP address when the handskahe occurs
Definition at line 72 of file UdpClientHandler.java.
                                           {
        Log.d(TAG,"update state");
        textViewState.setText(state);
    }
Referenced by com.example.trainawearapplication.UdpClientHandler.handleMessage().
Member Data Documentation
parent
MainActivity com.example.trainawearapplication.UdpClientHandler.parent [private]
Definition at line 30 of file UdpClientHandler.java.
Referenced by com.example.trainawearapplication.UdpClientHandler.UdpClientHandler().
UPDATE_END
final int com.example.trainawearapplication.UdpClientHandler.UPDATE_END = 3 [static]
Definition at line 29 of file UdpClientHandler.java.
UPDATE_MSG
final int com.example.trainawearapplication.UdpClientHandler.UPDATE_MSG = 1 [static]
Definition at line 27 of file UdpClientHandler.java.
Referenced by com.example.trainawearapplication.UdpClientHandler.handleMessage(), and com.example.trainawearapplication.ClientListen.run().
UPDATE_PLANK
final int com.example.trainawearapplication.UdpClientHandler.UPDATE_PLANK = 2 [static]
Definition at line 28 of file UdpClientHandler.java.
UPDATE_STATE
final int com.example.trainawearapplication.UdpClientHandler.UPDATE_STATE = 0 [static]
Definition at line 26 of file UdpClientHandler.java.
Referenced by com.example.trainawearapplication.UdpClientHandler.handleMessage(), com.example.trainawearapplication.ClientListen.run(), and com.example.trainawearapplication.ClientListen.sendState().
The documentation for this class was generated from the following file:
src/main/java/com/example/trainawearapplication/UdpClientHandler.java